In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
from IPython.core.display import HTML

In [2]:
import pandas as pd
from decimal import Decimal
# canvas
import os
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter, A4, landscape
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from num2words import num2words
from datetime import datetime
import pytz
indian = pytz.timezone('Asia/Kolkata')
from calendar import monthrange, month_name

In [2]:
from_date = '2021-01-01'
to_date = '2021-01-31'

final_dict = {}
business_type_ids = list(BusinessTypeOrderCategoryeMap.objects.filter(order_category_id=1, payment_option_id=1).order_by('business_type_id').values_list('business_type_id', flat=True))

date_wise_sale_list = list(SaleGroup.objects.filter(business__business_type_id__in=business_type_ids, date__range=[from_date, to_date], ordered_via_id__in=[1,3]).order_by('date').values_list('date', 'sale__product__short_name', 'sale__count', 'sale__cost', 'sale__product__productfinancecodemap__group_name', 'sale__product__quantity'))                                                          
date_wise_sale_columns = ['date', 'product', 'sale_count', 'sale_cost', 'product_type', 'product_quantity']
date_wise_sale_df = pd.DataFrame(date_wise_sale_list, columns=date_wise_sale_columns)

date_wise_sale_df = date_wise_sale_df.groupby(['date', 'product_type', 'product', 'product_quantity']).agg({'sale_count':sum, 'sale_cost': sum}).reset_index()
date_wise_sale_df['date'] = pd.to_datetime(date_wise_sale_df['date'], format='%Y-%m-%d').dt.strftime('%d-%m-%Y')


for index,data in date_wise_sale_df.iterrows():
    if not data['date'] in final_dict:
        data_dict = {}
        for product_finance_code in ProductFinanceCodeMap.objects.filter():
            if not product_finance_code.group_name in data_dict:
                data_dict[product_finance_code.group_name] = {}
            for product in list(ProductFinanceCodeMap.objects.filter(id=product_finance_code.id).values('product__short_name', 'product__quantity')):
                if not product['product__short_name'] in data_dict[product_finance_code.group_name]:
                    data_dict[product_finance_code.group_name][product['product__short_name']] = {
                        'sale_count': 0,
                        'sale_cost': 0,
                        'product_quantity': product['product__quantity'],
                        'sale_liter': 0
                    }
        final_dict[data['date']] = data_dict
        final_dict[data['date']]['total_liter'] = 0
        final_dict[data['date']]['total_cost'] = 0


    final_dict[data['date']][data['product_type']][data['product']]["sale_count"] = data['sale_count']
    final_dict[data['date']][data['product_type']][data['product']]["sale_cost"] = data.sale_cost
    final_dict[data['date']][data['product_type']][data['product']]["sale_liter"] = (Decimal(data.product_quantity) * Decimal(data.sale_count))/ 1000
    final_dict[data['date']]["total_liter"] += final_dict[data['date']][data['product_type']][data['product']]["sale_liter"]
    final_dict[data['date']]["total_cost"] += data.sale_cost

In [25]:
    file_name = str(from_date) + '_' + str(to_date) + 'daily_total_product_saale_report.pdf'
    file_path = os.path.join('static/media/monthly_report/', file_name)

    mycanvas = canvas.Canvas(file_path, pagesize=(11.694 * inch, 8.264 * inch))
    # ________Head_lines________#
    mycanvas.drawCentredString(405, 575, 'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')

    x = 45
    y = 500

    mycanvas.setFont('Helvetica-Bold', 11)
    mycanvas.line(x+75,y+35, x+700, y+35)
    mycanvas.line(x+75,y+35, x+75, y)
    mycanvas.line(x+345,y+35, x+345, y)
    mycanvas.line(x+525,y+35, x+525, y)
    mycanvas.line(x+700,y+35, x+700, y)

    mycanvas.drawCentredString(x+205,y+20,"MILK")
    mycanvas.drawCentredString(x+435,y+20,"CURD")
    mycanvas.drawCentredString(x+610,y+20,"BUTTER MILK")

    mycanvas.setFont('Helvetica', 11)
    mycanvas.drawCentredString(x-10,y,"S.NO")
    mycanvas.drawCentredString(x+40,y,"Date")
    mycanvas.drawCentredString(x+105-5,y,"TM500")
    mycanvas.drawCentredString(x+160-10,y,"STD250")
    mycanvas.drawCentredString(x+220-15,y,"STD500")
    mycanvas.drawCentredString(x+280-20,y,"FCM500")
    mycanvas.drawCentredString(x+345-30,y,"FCM1000")
    mycanvas.drawCentredString(x+410-34,y,"CURD100")
    mycanvas.drawCentredString(x+480-44,y,"CURD150")

    mycanvas.drawCentredString(x+550-55,y,"CURD500")
    mycanvas.drawCentredString(x+615-62,y,"BM200")
    mycanvas.drawCentredString(x+675-65,y,"BMJ200")
    mycanvas.drawCentredString(x+675,y,"BMJF")
    mycanvas.drawCentredString(x+745,y,"Total")

    mycanvas.line(x-25,y+15, x+775, y+15)
    mycanvas.line(x-25,y-10, x+775, y-10)

    total_litter = 0
    total_cost = 0

    tm_500_ltr = 0 
    sm_250_ltr = 0 
    sm_500_ltr = 0 
    fcm_500_ltr = 0 
    fcm_1000_ltr = 0 
    crd_100_ltr = 0 
    crd_150_ltr = 0 
    crd_500_ltr = 0 
    bm_200_ltr = 0  
    bmj_200_ltr = 0  
    bmjf_ltr = 0  

    tm_500_cst = 0
    sm_250_cst = 0
    sm_500_cst = 0
    fcm_500_cst = 0
    fcm_1000_cst = 0
    crd_100_cst = 0
    crd_150_cst = 0
    crd_500_cst = 0
    bm_200_cst =  0
    bmj_200_cst =  0
    bmjf_cst = 0


    mycanvas.setFont('Helvetica', 9)
    for index,data in enumerate(final_dict):
        mycanvas.drawString(x-15,y-25,str(index+1))
        mycanvas.drawString(x+20,y-25,str(data))
        mycanvas.drawRightString(x+120,y-25,str(final_dict[data]['Milk']['TM 500']['sale_liter']))
        tm_500_ltr += final_dict[data]['Milk']['TM 500']['sale_liter']

        mycanvas.drawRightString(x+170,y-25,str(final_dict[data]['Milk']['STD 250']['sale_liter']))
        sm_250_ltr += final_dict[data]['Milk']['STD 250']['sale_liter']

        mycanvas.drawRightString(x+225,y-25,str(final_dict[data]['Milk']['STD 500']['sale_liter']))
        sm_500_ltr += final_dict[data]['Milk']['STD 500']['sale_liter']

        mycanvas.drawRightString(x+280,y-25,str(final_dict[data]['Milk']['FCM 500']['sale_liter']))
        fcm_500_ltr += final_dict[data]['Milk']['FCM 500']['sale_liter']

        mycanvas.drawRightString(x+340,y-25,str(final_dict[data]['Milk']['FCM 1000']['sale_liter']))
        fcm_1000_ltr += final_dict[data]['Milk']['FCM 1000']['sale_liter']

        mycanvas.drawRightString(x+400,y-25,str(final_dict[data]['Curd']['Curd 100']['sale_liter']))
        crd_100_ltr += final_dict[data]['Curd']['Curd 100']['sale_liter']

        mycanvas.drawRightString(x+460,y-25,str(final_dict[data]['Curd']['Curd 150']['sale_liter']))
        crd_150_ltr += final_dict[data]['Curd']['Curd 150']['sale_liter']

        mycanvas.drawRightString(x+520,y-25,str(final_dict[data]['Curd']['Curd 500']['sale_liter']))
        crd_500_ltr += final_dict[data]['Curd']['Curd 500']['sale_liter']

        mycanvas.drawRightString(x+575,y-25,str(final_dict[data]['Butter Milk']['BM 200']['sale_liter']))
        bm_200_ltr += final_dict[data]['Butter Milk']['BM 200']['sale_liter']

        mycanvas.drawRightString(x+635,y-25,str(final_dict[data]['Butter Milk']['BMJar']['sale_liter']))
        bmj_200_ltr += final_dict[data]['Butter Milk']['BMJar']['sale_liter']

        mycanvas.drawRightString(x+695,y-25,str(final_dict[data]['Butter Milk']['BMJF']['sale_liter']))
        bmjf_ltr += final_dict[data]['Butter Milk']['BMJF']['sale_liter']

        mycanvas.drawRightString(x+770,y-25,str(final_dict[data]['total_liter']))   
        total_litter += final_dict[data]['total_liter']

        #lines 
        mycanvas.line(x-25,y+15, x-25, y-35)
        mycanvas.line(x+10,y+15, x+10, y-35)
        mycanvas.line(x+75,y+15, x+75, y-35)
        mycanvas.line(x+122,y+15, x+122, y-35)
        mycanvas.line(x+175,y+15, x+175, y-35)
        mycanvas.line(x+230,y+15, x+230, y-35)
        mycanvas.line(x+285,y+15, x+285, y-35)
        mycanvas.line(x+345,y+15, x+345, y-35)
        mycanvas.line(x+405,y+15, x+405, y-35)
        mycanvas.line(x+465,y+15, x+465, y-35)
        mycanvas.line(x+525,y+15, x+525, y-35)
        mycanvas.line(x+580,y+15, x+580, y-35)
        mycanvas.line(x+640,y+15, x+640, y-35)
        mycanvas.line(x+700,y+15, x+700, y-35)
        mycanvas.line(x+775,y+15, x+775, y-35)

        if (index + 1) % 22 == 0:
            mycanvas.line(x-25,y-35, x+775, y-35)
            mycanvas.showPage()
            mycanvas.drawCentredString(405, 575, 'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')
            x = 45
            y = 500

            mycanvas.setFont('Helvetica-Bold', 11)
            mycanvas.line(x+75,y+35, x+700, y+35)
            mycanvas.line(x+75,y+35, x+75, y)
            mycanvas.line(x+345,y+35, x+345, y)
            mycanvas.line(x+525,y+35, x+525, y)
            mycanvas.line(x+700,y+35, x+700, y)

            mycanvas.drawCentredString(x+205,y+20,"MILK")
            mycanvas.drawCentredString(x+435,y+20,"CURD")
            mycanvas.drawCentredString(x+610,y+20,"BUTTER MILK")

            mycanvas.setFont('Helvetica', 11)
            mycanvas.drawCentredString(x-10,y,"S.NO")
            mycanvas.drawCentredString(x+40,y,"Date")
            mycanvas.drawCentredString(x+105-5,y,"TM500")
            mycanvas.drawCentredString(x+160-10,y,"STD250")
            mycanvas.drawCentredString(x+220-15,y,"STD500")
            mycanvas.drawCentredString(x+280-20,y,"FCM500")
            mycanvas.drawCentredString(x+345-30,y,"FCM1000")
            mycanvas.drawCentredString(x+410-34,y,"CURD100")
            mycanvas.drawCentredString(x+480-44,y,"CURD150")

            mycanvas.drawCentredString(x+550-55,y,"CURD500")
            mycanvas.drawCentredString(x+615-62,y,"BM200")
            mycanvas.drawCentredString(x+675-65,y,"BMJ200")
            mycanvas.drawCentredString(x+675,y,"BMJF")
            mycanvas.drawCentredString(x+745,y,"Total")

            mycanvas.line(x-25,y+15, x+775, y+15)
            mycanvas.line(x-25,y-10, x+775, y-10)
            y += 20
            mycanvas.setFont('Helvetica', 9)

        y -= 20

    mycanvas.line(x-25,y-15, x+775, y-15)
    mycanvas.line(x+10,y-35, x+775, y-35)

    mycanvas.line(x+10,y-15, x+10, y-35)
    mycanvas.line(x+75,y-15, x+75, y-35)
    mycanvas.line(x+122,y-15, x+122, y-35)
    mycanvas.line(x+175,y-15, x+175, y-35)
    mycanvas.line(x+230,y-15, x+230, y-35)
    mycanvas.line(x+285,y-15, x+285, y-35)
    mycanvas.line(x+345,y-15, x+345, y-35)
    mycanvas.line(x+405,y-15, x+405, y-35)
    mycanvas.line(x+465,y-15, x+465, y-35)
    mycanvas.line(x+525,y-15, x+525, y-35)
    mycanvas.line(x+580,y-15, x+580, y-35)
    mycanvas.line(x+640,y-15, x+640, y-35)
    mycanvas.line(x+700,y-15, x+700, y-35)
    mycanvas.line(x+775,y-15, x+775, y-35)

    mycanvas.line(x+700,y-15, x+700, y-35)
    mycanvas.line(x+775,y-15, x+775, y-35)


    mycanvas.setFont('Helvetica', 8)
    mycanvas.drawRightString(x+70,y-30,"Total Litre")
    mycanvas.drawRightString(x+120,y-30,str(tm_500_ltr))
    mycanvas.drawRightString(x+170,y-30,str(sm_250_ltr))
    mycanvas.drawRightString(x+227,y-30,str(sm_500_ltr))
    mycanvas.drawRightString(x+282,y-30,str(fcm_500_ltr))
    mycanvas.drawRightString(x+340,y-30,str(fcm_1000_ltr))
    mycanvas.drawRightString(x+400,y-30,str(crd_100_ltr))
    mycanvas.drawRightString(x+460,y-30,str(crd_150_ltr))
    mycanvas.drawRightString(x+520,y-30,str(crd_500_ltr))
    mycanvas.drawRightString(x+575,y-30,str(bm_200_ltr))
    mycanvas.drawRightString(x+635,y-30,str(bmj_200_ltr))
    mycanvas.drawRightString(x+695,y-30,str(bmjf_ltr))
    mycanvas.drawRightString(x+770,y-30,str(total_litter))

    mycanvas.showPage()


    # --------------------------------------------------for cost-------------------------------------------
    mycanvas.drawCentredString(405, 575, 'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')

    x = 45
    y = 500

    mycanvas.setFont('Helvetica-Bold', 11)
    mycanvas.line(x+75,y+35, x+700, y+35)
    mycanvas.line(x+75,y+35, x+75, y)
    mycanvas.line(x+345,y+35, x+345, y)
    mycanvas.line(x+525,y+35, x+525, y)
    mycanvas.line(x+700,y+35, x+700, y)

    mycanvas.drawCentredString(x+205,y+20,"MILK")
    mycanvas.drawCentredString(x+435,y+20,"CURD")
    mycanvas.drawCentredString(x+610,y+20,"BUTTER MILK")

    mycanvas.setFont('Helvetica', 11)
    mycanvas.drawCentredString(x-10,y,"S.NO")
    mycanvas.drawCentredString(x+40,y,"Date")
    mycanvas.drawCentredString(x+105-5,y,"TM500")
    mycanvas.drawCentredString(x+160-10,y,"STD250")
    mycanvas.drawCentredString(x+220-15,y,"STD500")
    mycanvas.drawCentredString(x+280-20,y,"FCM500")
    mycanvas.drawCentredString(x+345-30,y,"FCM1000")
    mycanvas.drawCentredString(x+410-34,y,"CURD100")
    mycanvas.drawCentredString(x+480-44,y,"CURD150")

    mycanvas.drawCentredString(x+550-55,y,"CURD500")
    mycanvas.drawCentredString(x+615-62,y,"BM200")
    mycanvas.drawCentredString(x+675-65,y,"BMJ200")
    mycanvas.drawCentredString(x+675,y,"BMJF")
    mycanvas.drawCentredString(x+745,y,"Total")

    mycanvas.line(x-25,y+15, x+775, y+15)
    mycanvas.line(x-25,y-10, x+775, y-10)

    mycanvas.setFont('Helvetica', 9)
    for index,data in enumerate(final_dict):
        print(data)
        mycanvas.drawString(x-15,y-25,str(index+1))
        mycanvas.drawString(x+20,y-25,str(data))
        mycanvas.drawRightString(x+120,y-25,str(final_dict[data]['Milk']['TM 500']['sale_cost']))
        tm_500_cst += final_dict[data]['Milk']['TM 500']['sale_cost']

        mycanvas.drawRightString(x+170,y-25,str(final_dict[data]['Milk']['STD 250']['sale_cost']))
        sm_250_cst += final_dict[data]['Milk']['STD 250']['sale_cost'] 

        mycanvas.drawRightString(x+225,y-25,str(final_dict[data]['Milk']['STD 500']['sale_cost']))
        sm_500_cst += final_dict[data]['Milk']['STD 500']['sale_cost']    

        mycanvas.drawRightString(x+280,y-25,str(final_dict[data]['Milk']['FCM 500']['sale_cost']))
        fcm_500_cst += final_dict[data]['Milk']['FCM 500']['sale_cost']    

        mycanvas.drawRightString(x+340,y-25,str(final_dict[data]['Milk']['FCM 1000']['sale_cost']))
        fcm_1000_cst += final_dict[data]['Milk']['FCM 1000']['sale_cost']   

        mycanvas.drawRightString(x+400,y-25,str(final_dict[data]['Curd']['Curd 100']['sale_cost']))
        crd_100_cst += final_dict[data]['Curd']['Curd 100']['sale_cost']   

        mycanvas.drawRightString(x+460,y-25,str(final_dict[data]['Curd']['Curd 150']['sale_cost']))
        crd_150_cst += final_dict[data]['Curd']['Curd 150']['sale_cost']   

        mycanvas.drawRightString(x+520,y-25,str(final_dict[data]['Curd']['Curd 500']['sale_cost']))
        crd_500_cst += final_dict[data]['Curd']['Curd 500']['sale_cost']   

        mycanvas.drawRightString(x+575,y-25,str(final_dict[data]['Butter Milk']['BM 200']['sale_cost']))
        bm_200_cst += final_dict[data]['Butter Milk']['BM 200']['sale_cost']    

        mycanvas.drawRightString(x+635,y-25,str(final_dict[data]['Butter Milk']['BMJar']['sale_cost']))
        bmj_200_cst += final_dict[data]['Butter Milk']['BMJar']['sale_cost']   

        mycanvas.drawRightString(x+695,y-25,str(final_dict[data]['Butter Milk']['BMJF']['sale_cost']))
        bmjf_cst += final_dict[data]['Butter Milk']['BMJF']['sale_cost']     

        mycanvas.drawRightString(x+770,y-25,str(final_dict[data]['total_cost']))
        total_cost += final_dict[data]['total_cost']

        #lines 
        mycanvas.line(x-25,y+15, x-25, y-35)
        mycanvas.line(x+10,y+15, x+10, y-35)
        mycanvas.line(x+75,y+15, x+75, y-35)
        mycanvas.line(x+122,y+15, x+122, y-35)
        mycanvas.line(x+175,y+15, x+175, y-35)
        mycanvas.line(x+230,y+15, x+230, y-35)
        mycanvas.line(x+285,y+15, x+285, y-35)
        mycanvas.line(x+345,y+15, x+345, y-35)
        mycanvas.line(x+405,y+15, x+405, y-35)
        mycanvas.line(x+465,y+15, x+465, y-35)
        mycanvas.line(x+525,y+15, x+525, y-35)
        mycanvas.line(x+580,y+15, x+580, y-35)
        mycanvas.line(x+640,y+15, x+640, y-35)
        mycanvas.line(x+700,y+15, x+700, y-35)
        mycanvas.line(x+775,y+15, x+775, y-35)

        if (index + 1) % 22 == 0:
            mycanvas.line(x-25,y-35, x+775, y-35)
            mycanvas.showPage()
            mycanvas.drawCentredString(405, 575, 'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')
            x = 45
            y = 500

            mycanvas.setFont('Helvetica-Bold', 11)
            mycanvas.line(x+75,y+35, x+700, y+35)
            mycanvas.line(x+75,y+35, x+75, y)
            mycanvas.line(x+345,y+35, x+345, y)
            mycanvas.line(x+525,y+35, x+525, y)
            mycanvas.line(x+700,y+35, x+700, y)

            mycanvas.drawCentredString(x+205,y+20,"MILK")
            mycanvas.drawCentredString(x+435,y+20,"CURD")
            mycanvas.drawCentredString(x+610,y+20,"BUTTER MILK")

            mycanvas.setFont('Helvetica', 11)
            mycanvas.drawCentredString(x-10,y,"S.NO")
            mycanvas.drawCentredString(x+40,y,"Date")
            mycanvas.drawCentredString(x+105-5,y,"TM500")
            mycanvas.drawCentredString(x+160-10,y,"STD250")
            mycanvas.drawCentredString(x+220-15,y,"STD500")
            mycanvas.drawCentredString(x+280-20,y,"FCM500")
            mycanvas.drawCentredString(x+345-30,y,"FCM1000")
            mycanvas.drawCentredString(x+410-34,y,"CURD100")
            mycanvas.drawCentredString(x+480-44,y,"CURD150")

            mycanvas.drawCentredString(x+550-55,y,"CURD500")
            mycanvas.drawCentredString(x+615-62,y,"BM200")
            mycanvas.drawCentredString(x+675-65,y,"BMJ200")
            mycanvas.drawCentredString(x+675,y,"BMJF")
            mycanvas.drawCentredString(x+745,y,"Total")

            mycanvas.line(x-25,y+15, x+775, y+15)
            mycanvas.line(x-25,y-10, x+775, y-10)
            y += 20
            mycanvas.setFont('Helvetica', 9)

        y -= 20

    mycanvas.line(x-25,y-15, x+775, y-15)
    mycanvas.line(x+10,y-35, x+775, y-35)

    mycanvas.line(x+10,y-15, x+10, y-35)
    mycanvas.line(x+75,y-15, x+75, y-35)
    mycanvas.line(x+122,y-15, x+122, y-35)
    mycanvas.line(x+175,y-15, x+175, y-35)
    mycanvas.line(x+230,y-15, x+230, y-35)
    mycanvas.line(x+285,y-15, x+285, y-35)
    mycanvas.line(x+345,y-15, x+345, y-35)
    mycanvas.line(x+405,y-15, x+405, y-35)
    mycanvas.line(x+465,y-15, x+465, y-35)
    mycanvas.line(x+525,y-15, x+525, y-35)
    mycanvas.line(x+580,y-15, x+580, y-35)
    mycanvas.line(x+640,y-15, x+640, y-35)
    mycanvas.line(x+700,y-15, x+700, y-35)
    mycanvas.line(x+775,y-15, x+775, y-35)

    mycanvas.line(x+700,y-15, x+700, y-35)
    mycanvas.line(x+775,y-15, x+775, y-35)


    mycanvas.setFont('Helvetica', 8)
    mycanvas.drawRightString(x+70,y-30,"Total Cost")
    mycanvas.drawRightString(x+120,y-30,str(tm_500_cst))
    mycanvas.drawRightString(x+170,y-30,str(sm_250_cst))
    mycanvas.drawRightString(x+227,y-30,str(sm_500_cst))
    mycanvas.drawRightString(x+282,y-30,str(fcm_500_cst))
    mycanvas.drawRightString(x+340,y-30,str(fcm_1000_cst))
    mycanvas.drawRightString(x+400,y-30,str(crd_100_cst))
    mycanvas.drawRightString(x+460,y-30,str(crd_150_cst))
    mycanvas.drawRightString(x+520,y-30,str(crd_500_cst))
    mycanvas.drawRightString(x+575,y-30,str(bm_200_cst))
    mycanvas.drawRightString(x+635,y-30,str(bmj_200_cst))
    mycanvas.drawRightString(x+695,y-30,str(bmjf_cst))
    mycanvas.drawRightString(x+770,y-30,str(total_cost))


    mycanvas.save()
    
    str(names)[1:-1]

NameError: name 'final_dict' is not defined

In [48]:
product_dict = {
    '1':['tm500_litre', 'tmcan_litre', 'smcan_litre', 'fcm1000_litre', 'fcm500_litre', 'std500_litre', 'std250_litre'],
    '2':['cupcurd_kgs', 'curd150_kgs', 'curd500_kgs'],
    '3':['buttermilk200_litre', 'bm_jar200_litre', 'bmjf200_litre']
}
str(product_dict['1'])[1:-1]

print(', '.join('mor_route__dailysessionllybusinessllysale__{}'.format(i) for i in product_dict['1']))

mor_route__dailysessionllybusinessllysale__tm500_litre, mor_route__dailysessionllybusinessllysale__tmcan_litre, mor_route__dailysessionllybusinessllysale__smcan_litre, mor_route__dailysessionllybusinessllysale__fcm1000_litre, mor_route__dailysessionllybusinessllysale__fcm500_litre, mor_route__dailysessionllybusinessllysale__std500_litre, mor_route__dailysessionllybusinessllysale__std250_litre

In [4]:
from_date = '2021-04-01' 
to_date = '2021-04-21'
product_type_id = 3
mor_sale_obj = RouteGroupMap.objects.filter(mor_route__dailysessionllybusinessllysale__delivery_date__range=[from_date, to_date])
eve_sale_obj = RouteGroupMap.objects.filter(eve_route__dailysessionllybusinessllysale__delivery_date__range=[from_date, to_date])

if product_type_id == 1:
    mor_route_group_vlaues = mor_sale_obj.values_list('mor_route__dailysessionllybusinessllysale__tm500_litre', 'mor_route__dailysessionllybusinessllysale__fcm1000_litre', 'mor_route__dailysessionllybusinessllysale__fcm500_litre', 'mor_route__dailysessionllybusinessllysale__std500_litre', 'mor_route__dailysessionllybusinessllysale__std250_litre', 'mor_route__dailysessionllybusinessllysale__tmcan_litre', 'mor_route__dailysessionllybusinessllysale__smcan_litre', 'mor_route__name', 'route_city__name')                                                                                    
    eve_route_group_vlaues = eve_sale_obj.values_list('eve_route__dailysessionllybusinessllysale__tm500_litre', 'eve_route__dailysessionllybusinessllysale__fcm1000_litre', 'eve_route__dailysessionllybusinessllysale__fcm500_litre', 'eve_route__dailysessionllybusinessllysale__std500_litre', 'eve_route__dailysessionllybusinessllysale__std250_litre', 'eve_route__dailysessionllybusinessllysale__tmcan_litre', 'eve_route__dailysessionllybusinessllysale__smcan_litre', 'eve_route__name', 'route_city__name')
    route_group_columns = ['TM 500', 'FCM 1000', 'FCM 500', 'SM 500', 'SM 250', 'TM Can', 'SM Can', 'Route Name', 'route_city_name']
    mor_sale_df = pd.DataFrame(mor_route_group_vlaues, columns = route_group_columns)
    eve_sale_df = pd.DataFrame(eve_route_group_vlaues, columns = route_group_columns)
    
    if mor_route_group_vlaues:
        mor_sale_df = mor_sale_df.groupby(['Route Name', 'route_city_name']).agg({'TM 500':sum, 'FCM 1000':sum, 'FCM 500':sum, 'SM 500':sum, 'SM 250':sum, 'TM Can':sum, 'SM Can':sum}).reset_index()
        mor_sale_df['Route Name'] = mor_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues:
        eve_sale_df = eve_sale_df.groupby(['Route Name', 'route_city_name']).agg({'TM 500':sum, 'FCM 1000':sum, 'FCM 500':sum, 'SM 500':sum, 'SM 250':sum, 'TM Can':sum, 'SM Can':sum}).reset_index()
        eve_sale_df['Route Name'] = eve_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues or mor_route_group_vlaues:
        final_df = pd.concat([mor_sale_df, eve_sale_df])
        final_df = final_df.groupby(['Route Name', 'route_city_name']).agg({'TM 500':sum, 'FCM 1000':sum, 'FCM 500':sum, 'SM 500':sum, 'SM 250':sum, 'TM Can':sum, 'SM Can':sum}).reset_index()
    else:
        print('No Data Avaliable')
    
if product_type_id == 2:
    mor_route_group_vlaues = mor_sale_obj.values_list('mor_route__dailysessionllybusinessllysale__cupcurd_kgs', 'mor_route__dailysessionllybusinessllysale__curd150_kgs', 'mor_route__dailysessionllybusinessllysale__curd500_kgs', 'mor_route__name', 'route_city__name')                                                                                    
    eve_route_group_vlaues = eve_sale_obj.values_list('eve_route__dailysessionllybusinessllysale__cupcurd_kgs', 'eve_route__dailysessionllybusinessllysale__curd150_kgs', 'eve_route__dailysessionllybusinessllysale__curd500_kgs', 'eve_route__name', 'route_city__name')
    route_group_columns = ['CURD 100', 'CURD 150', 'CURD 500', 'Route Name', 'route_city_name']
    mor_sale_df = pd.DataFrame(mor_route_group_vlaues, columns = route_group_columns)
    eve_sale_df = pd.DataFrame(eve_route_group_vlaues, columns = route_group_columns)
    
    if mor_route_group_vlaues:
        mor_sale_df = mor_sale_df.groupby(['Route Name', 'route_city_name']).agg({'CURD 100':sum, 'CURD 150':sum, 'CURD 500':sum}).reset_index()
        mor_sale_df['Route Name'] = mor_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues:
        eve_sale_df = eve_sale_df.groupby(['Route Name', 'route_city_name']).agg({'CURD 100':sum, 'CURD 150':sum, 'CURD 500':sum}).reset_index()
        eve_sale_df['Route Name'] = eve_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues or mor_route_group_vlaues:
        final_df = pd.concat([mor_sale_df, eve_sale_df])
        final_df = final_df.groupby(['Route Name', 'route_city_name']).agg({'CURD 100':sum, 'CURD 150':sum, 'CURD 500':sum}).reset_index()
    else:
        print('No Data Avaliable')
    
if product_type_id == 3:
    mor_route_group_vlaues = mor_sale_obj.values_list('mor_route__dailysessionllybusinessllysale__buttermilk200_litre', 'mor_route__dailysessionllybusinessllysale__bm_jar200_litre', 'mor_route__dailysessionllybusinessllysale__bmjf200_litre', 'mor_route__name', 'route_city__name')                                                                                    
    eve_route_group_vlaues = eve_sale_obj.values_list('eve_route__dailysessionllybusinessllysale__buttermilk200_litre', 'eve_route__dailysessionllybusinessllysale__bm_jar200_litre', 'eve_route__dailysessionllybusinessllysale__bmjf200_litre', 'eve_route__name', 'route_city__name')
    route_group_columns = ['BM 200', 'BM Jar', 'BMJF', 'Route Name', 'route_city_name']
    mor_sale_df = pd.DataFrame(mor_route_group_vlaues, columns = route_group_columns)
    eve_sale_df = pd.DataFrame(eve_route_group_vlaues, columns = route_group_columns)
    
    if mor_route_group_vlaues:
        mor_sale_df = mor_sale_df.groupby(['Route Name', 'route_city_name']).agg({'BM 200':sum, 'BM Jar':sum, 'BMJF':sum}).reset_index()
        mor_sale_df['Route Name'] = mor_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues:
        eve_sale_df = eve_sale_df.groupby(['Route Name', 'route_city_name']).agg({'BM 200':sum, 'BM Jar':sum, 'BMJF':sum}).reset_index()
        eve_sale_df['Route Name'] = eve_sale_df['Route Name'].str[:-4]
        
    if eve_route_group_vlaues or mor_route_group_vlaues:
        final_df = pd.concat([mor_sale_df, eve_sale_df])
        final_df = final_df.groupby(['Route Name', 'route_city_name']).agg({'BM 200':sum, 'BM Jar':sum, 'BMJF':sum}).reset_index()
    else:
        print('No Data Avaliable')

final_df.index += 1

# row wise total
final_df['TOTAL'] = final_df.sum(numeric_only=True,axis=1)

# column wise total
final_df.loc['',2:]= final_df.iloc[:, 2:].sum(numeric_only=True, axis=0)
final_df.iloc[-1, final_df.columns.get_loc('Route Name')] = 'Grand Total'

#grand_total df
grand_df = final_df[final_df['Route Name'] == 'Grand Total' ]

final_df.type()

KeyError: 'Route Name'

In [10]:


# product_list = list(ProductFinanceCodeMap.objects.filter(id=product_type_id).values_list('product', flat=True))


# # Mornig Route Sale Df
# mor_route_group_vlaues = list(RouteGroupMap.objects.filter(mor_route__salegroup__date__range=[from_date, to_date], mor_route__salegroup__sale__product_id__in=product_list).values_list( 'mor_route__name', 'mor_route__salegroup__sale__product__short_name', 'mor_route__salegroup__sale__product__quantity', 'mor_route__salegroup__sale__count', 'route_city__name'))    
# mor_route_group_columns = ['route_name', 'product', 'product_quantity', 'sale_count', 'route_city_name']
# mor_sale_df = pd.DataFrame(mor_route_group_vlaues, columns = mor_route_group_columns)

# if mor_route_group_vlaues:
#     mor_sale_df['total_litre'] = (mor_sale_df['product_quantity'].astype(float) * mor_sale_df['sale_count']) / 1000

#     mor_sale_df = mor_sale_df.drop(columns=['product_quantity', 'sale_count'])
#     mor_sale_df = mor_sale_df.groupby(['route_name', 'product', 'route_city_name']).agg({'total_litre': sum}).reset_index()

#     mor_sale_df['route_name'] = mor_sale_df['route_name'].str[:-4]

# # Evening Route Wise Sale Df
# eve_route_group_vlaues = list(RouteGroupMap.objects.filter(eve_route__salegroup__date__range=[from_date, to_date], eve_route__salegroup__sale__product_id__in=product_list).values_list( 'eve_route__name', 'eve_route__salegroup__sale__product__short_name', 'eve_route__salegroup__sale__product__quantity', 'eve_route__salegroup__sale__count', 'route_city__name'))      
# eve_route_group_columns = ['route_name', 'product', 'product_quantity', 'sale_count', 'route_city_name']
# eve_sale_df = pd.DataFrame(eve_route_group_vlaues, columns = eve_route_group_columns)

# if eve_route_group_vlaues:
#     eve_sale_df['total_litre'] = (eve_sale_df['product_quantity'].astype(float) * eve_sale_df['sale_count']) / 1000

#     eve_sale_df = eve_sale_df.drop(columns=['product_quantity', 'sale_count'])
#     eve_sale_df = eve_sale_df.groupby(['route_name', 'product', 'route_city_name']).agg({'total_litre': sum}).reset_index()

#     eve_sale_df['route_name'] = eve_sale_df['route_name'].str[:-4]

# if eve_route_group_vlaues or mor_route_group_vlaues:
#     final_df = pd.concat([mor_sale_df, eve_sale_df])
#     final_df = final_df.groupby(['route_name', 'product', 'route_city_name']).agg({'total_litre': sum}).reset_index()

#     #convert_groupby_table_product_cost_row_wise_value_into_column(using_pandas_pivot_table)
#     final_df = pd.pivot_table(final_df, index=['route_name', 'route_city_name'], columns='product', aggfunc=min, fill_value=0)

#     #convert_pivot_table_to_normal_df
#     final_df.columns = final_df.columns.droplevel(0) #remove amount
#     final_df.columns.name = None  #remove categories
#     final_df = final_df.reset_index() #index to columns
# else:
#     print('No Data Avaliable')

# final_df.index += 1

# # row wise total
# final_df['TOTAL'] = final_df.sum(axis=1)

# # column wise total
# final_df.loc['',2:]= final_df.iloc[:, 2:].sum(numeric_only=True, axis=0)
# final_df.iloc[-1, final_df.columns.get_loc('route_name')] = 'Grand Total'

# #grand_total df
# grand_df = final_df[final_df['route_name'] == 'Grand Total' ]

# -----------------------------------------------------------------------Excel part
writer = pd.ExcelWriter(str("static/media/") + f'route_wise_sale_details_for_{from_date}_to_{to_date}.xlsx', engine="xlsxwriter")

spacing = 4

# assigning that sheet to obj
workbook = writer.book
worksheet = workbook.add_worksheet('CITY ROUTE WISE SALE')
writer.sheets['CITY ROUTE WISE SALE'] = worksheet

merge_dict = {
    "bold": 1,
    "border": 1,
    "align": "center",
    "valign": "vcenter",
    "fg_color": "yellow",
}

merge_dict2 = {
    "bold": 1,
    "border": 1,
    "align": "center",
    "valign": "vcenter",
    "fg_color": "cyan",
}


merge_format = workbook.add_format(merge_dict)
merge_format2 = workbook.add_format(merge_dict2)

# Merge cells.
product_len = len(product_list)
ltr = chr(ord('@')+product_len+3)
ltr = ltr+"2"
worksheet.merge_range(f"A2:{ltr}", f"City Wise Sale Report For {from_date} to {to_date}", merge_format)

format1 = workbook.add_format({"num_format": "#,##0.000"})

# Set the column width and format.
worksheet.set_column("C:H", 18, format1)
worksheet.set_column(1, 7, 20)

for route_city in list(set(final_df['route_city_name'].dropna())):
    merge_dict['fg_color'] = 'blue'

    ltr1 = 'A'+str(spacing)
    ltr2 = 'B'+str(spacing)

    worksheet.merge_range(f"{ltr1}:{ltr2}", f"{route_city}", merge_format2)
    df = final_df[final_df['route_city_name'] == route_city]
    df = df.drop(columns=['route_city_name'])
    df = df.reset_index(drop=True)
    df.index += 1
    df.loc['',0:]= df.iloc[:, 1:].sum(numeric_only=True, axis=0)
    df.iloc[-1, df.columns.get_loc('route_name')] = 'Sub Total'
    df.to_excel(writer,sheet_name='CITY ROUTE WISE SALE',startrow=spacing)
    spacing += df.shape[0] + 4

grand_df = grand_df.drop(columns=['route_city_name']).rename(columns={'route_name': ''})
grand_df.to_excel(writer,sheet_name='CITY ROUTE WISE SALE',startrow=spacing)
writer.save()

tm500_litre tmcan_litre smcan_litre fcm1000_litre fcm500_litre std500_litre std250_litre

<ipython-input-10-668374c19af5>:62: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  final_df.loc['',2:]= final_df.iloc[:, 2:].sum(numeric_only=True, axis=0)
<ipython-input-10-668374c19af5>:121: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  df.loc['',0:]= df.iloc[:, 1:].sum(numeric_only=True, axis=0)

###  Price Udate Script

In [11]:
reduesed_price = 3
product_price_df = pd.DataFrame(list(Product.objects.filter(group_id=1).values('id', 'quantity')))
product_price_df['reduesed_price'] = float(reduesed_price) / (float(1000)/product_price_df['quantity'].astype(float))
price_dict = product_price_df.groupby('id').apply(lambda x: x.to_dict('r')[0]).to_dict()

for product_obj in Product.objects.filter(group_id=1):
    product_obj.mrp -= Decimal(price_dict[product_obj.id]['reduesed_price'])
#     product_obj.save()
for buainess_product_obj in BusinessWiseProductDiscount.objects.filter(product__group_id=1):
    buainess_product_obj.discounted_price -= Decimal(price_dict[buainess_product_obj.product_id]['reduesed_price'])
#     buainess_product_obj.save()
for customer_product_obj in ICustomerTypeWiseProductDiscount.objects.filter(product__group_id=1):
    customer_product_obj.discounted_price -= Decimal(price_dict[customer_product_obj.product_id]['reduesed_price'])
#     customer_product_obj.save()

###  ICustomer Salegroup Price Update Script

In [21]:
icustomer_sale_group_obj = ICustomerSaleGroup.objects.filter(date__month=6, time_created__date__gte='2021-05-4')
for icustomer_sale_group in icustomer_sale_group_obj:
    total_coat_for_month = 0
    total_cost = 0
    user_product_df = serve_product_dict(icustomer_sale_group.business.user_profile)
    user_product_dict = user_product_df.groupby('product_id').apply(lambda x: x.to_dict('r')[0]).to_dict()
    customer_sale_obj = ICustomerSale.objects.filter(icustomer_sale_group_id=icustomer_sale_group.id)
    for sale in customer_sale_obj:
        if sale.product.group_id == 1:
            updated_cost = user_product_dict[sale.product.id]['product_mrp'] * Decimal(sale.count) 
            cost_for_month = updated_cost * 30
            sale.cost = updated_cost
            sale.cost_for_month = cost_for_month
            total_cost += updated_cost
            total_coat_for_month += cost_for_month
#             sale.save()
        else:
            total_cost += sale.cost
            total_coat_for_month += sale.cost_for_month
            
    add_to_wallet_amount = icustomer_sale_group.total_cost_for_month - total_coat_for_month
    if add_to_wallet_amount != 0 :
        customer_wallet_obj = ICustomerWallet.objects.get(customer_id=icustomer_sale_group.icustomer_id)
        customer_wallet_obj.current_balance += add_to_wallet_amount
#         customer_wallet_obj.save()
    icustomer_sale_group.total_cost = total_cost
    icustomer_sale_group.product_amount = total_cost
    icustomer_sale_group.total_cost_for_month = total_coat_for_month
#     icustomer_sale_group.save()

### Sale Group Price Update Script

In [18]:
def serve_product_dict(user_profile_id):    
    business_id = BusinessAgentMap.objects.get(business__user_profile_id=user_profile_id, is_active=True).business_id
    business_type_id = Business.objects.get(id=business_id).business_type_id
    commission_product_ids = list(
        BusinessProductConcessionMap.objects.filter(business_type_id=business_type_id, product__is_active=True,
                                                    concession_type_id=1).values_list(
            'product_id', flat=True))
    discount_product_ids = list(
        BusinessProductConcessionMap.objects.filter(business_type_id=business_type_id, product__is_active=True,
                                                    concession_type_id=2).values_list(
            'product_id', flat=True))
    product_obj = Product.objects.filter(is_active=True, id__in=commission_product_ids).order_by(
        'display_ordinal').exclude(group_id=3)
    product_list = list(product_obj.values_list('id', 'group', 'group__name', 'name', 'short_name', 'code', 'unit',
                                                'unit__display_name', 'description', 'quantity', 'mrp',
                                                'gst_percent', 'color', 'minimum_quantity'))
    product_column = ['product_id', 'product_group_id', 'product_group_name', 'product_name', 'product_short_name',
                      'product_code', 'unit_id', 'unit_name', 'description', 'product_quantity', 'product_mrp',
                      'gst_percent', 'color', 'minimum_quantity']
    product_df = pd.DataFrame(product_list, columns=product_column)
    if business_type_id == 1 or business_type_id == 2 or business_type_id == 3 or business_type_id == 9 or business_type_id == 11:
        discounted_product_obj = BusinessTypeWiseProductDiscount.objects.filter(business_type_id=business_type_id,
                                                                                product__is_active=True,
                                                                                product_id__in=discount_product_ids).order_by(
            'product__display_ordinal').exclude(product__group_id=3)
        discounted_product_list = list(
            discounted_product_obj.values_list('product_id', 'product__group', 'product__group__name',
                                               'product__name', 'product__short_name', 'product__code',
                                               'product__unit',
                                               'product__unit__display_name', 'product__description',
                                               'product__quantity', 'discounted_price', 'product__gst_percent',
                                               'product__color', 'product__minimum_quantity'))
        discounted_product_column = ['product_id', 'product_group_id', 'product_group_name', 'product_name',
                                     'product_short_name',
                                     'product_code', 'unit_id', 'unit_name', 'description', 'product_quantity',
                                     'product_mrp',
                                     'gst_percent', 'color', 'minimum_quantity']
        discounted_product_df = pd.DataFrame(discounted_product_list, columns=discounted_product_column)
    else:
        discounted_product_obj = BusinessWiseProductDiscount.objects.filter(business_id=business_id,
                                                                            product__is_active=True,
                                                                            product_id__in=discount_product_ids).order_by(
            'product__display_ordinal').exclude(product__group_id=3)
        discounted_product_list = list(
            discounted_product_obj.values_list('product_id', 'product__group', 'product__group__name',
                                               'product__name', 'product__short_name', 'product__code',
                                               'product__unit',
                                               'product__unit__display_name', 'product__description',
                                               'product__quantity', 'discounted_price', 'product__gst_percent',
                                               'product__color', 'product__minimum_quantity'))
        discounted_product_column = ['product_id', 'product_group_id', 'product_group_name', 'product_name',
                                     'product_short_name',
                                     'product_code', 'unit_id', 'unit_name', 'description', 'product_quantity',
                                     'product_mrp',
                                     'gst_percent', 'color', 'minimum_quantity']
        discounted_product_df = pd.DataFrame(discounted_product_list, columns=discounted_product_column)
    final_product_df = product_df.merge(discounted_product_df, how="outer")
    loose_milk_obj = ProductQuantityVariationPrice.objects.filter(min_quantity=1, product__is_active=True).order_by(
        'product__display_ordinal')
    loose_milk_list = list(
        loose_milk_obj.values_list('product_id', 'product__group', 'product__group__name', 'product__name',
                                   'product__short_name', 'product__code', 'product__unit',
                                   'product__unit__display_name', 'product__description', 'product__quantity', 'mrp',
                                   'product__gst_percent', 'product__color', 'product__minimum_quantity'))
    loose_milk_column = ['product_id', 'product_group_id', 'product_group_name', 'product_name', 'product_short_name',
                         'product_code', 'unit_id', 'unit_name', 'description', 'product_quantity', 'product_mrp',
                         'gst_percent', 'color', 'minimum_quantity']
    loose_milk_df = pd.DataFrame(loose_milk_list, columns=loose_milk_column)
    final_product_df = final_product_df.merge(loose_milk_df, how="outer")
    final_product_df = final_product_df.fillna(0)
    return final_product_df

In [30]:
business_type_list = list(BusinessTypeOrderCategoryeMap.objects.filter(order_category_id=1, payment_option_id=1).values_list('business_type_id', flat=True))
sale_group_obj = SaleGroup.objects.filter(date__gte='2021-05-10', business__code='2658')

for sale_group in sale_group_obj:
    total_cost = 0
    user_product_df = serve_product_dict(sale_group.business.user_profile)
    user_product_dict = user_product_df.groupby('product_id').apply(lambda x: x.to_dict('r')[0]).to_dict()
    sale_obj = Sale.objects.filter(sale_group_id=sale_group.id)
    for sale in sale_obj:
        if sale.product.group_id == 1:
            updated_cost = user_product_dict[sale.product.id]['product_mrp'] * Decimal(sale.count) 
            sale.cost = updated_cost
            total_cost += updated_cost
#             sale.save()
        else:
            total_cost += sale.cost
    add_to_wallet_amount = sale_group.total_cost - total_cost
    if add_to_wallet_amount != 0 :
        if sale_group.business.business_type_id in business_type_list:
            agent_id = BusinessAgentMap.objects.get(business_id=sale_group.business_id).agent_id
            print(agent_id)
            agent_wallet_obj = AgentWallet.objects.get(agent_id=agent_id)
            agent_wallet_obj.current_balance += add_to_wallet_amount
#             agent_wallet_obj.save()
    sale_group.total_cost = total_cost
#     sale_group.save()

2641

In [2]:
sale_group_obj

NameError: name 'sale_group_obj' is not defined

In [5]:



def run_pdf_script():

    from_date = '2021-01-01'
    to_date = '2021-01-01'

    date_list = pd.date_range(start=from_date,end=to_date)
    data_dict = {
        "product":{
            "tm":{
                "Resived From Diary": 0,
                "Leakage" : 0,
                "TIRUPPUR Leakage":0,
                "Returned" : 0,
                "Net Recived" : 0
            },
            "std500":{
                "Resived From Diary": 0,
                "Leakage" : 0,
                "TIRUPPUR Leakage":0,
                "Returned" : 0,
                "Net Recived" : 0
            },
            "std250":{
                "Resived From Diary": 0,
                "Leakage" : 0,
                "TIRUPPUR Leakage":0,
                "Returned" : 0,
                "Net Recived" : 0
            },
            "fcm":{
                "Resived From Diary": 0,
                "Leakage" : 0,
                "TIRUPPUR Leakage":0,
                "Returned" : 0,
                "Net Recived" : 0
            },
        },
        "union_sale" : {},
        "Coimbatore Account" : {
            "Agent Cash":{
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Agent Card" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Union Booth Cash" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Union Booth Card" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Pvt Institutes" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Govt Institutes" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Society" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            },
            "Can Milk Buyer" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total": 0
            },
            "Kerala" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total": 0
            },
        },
        "Costs" : {
            "product":{
                "tm":{
                    "Resived From Diary": 0,
                    "Leakage" : 0,
                    "Returned" : 0,
                    "Net Recived" : 0
                },
                "std500":{
                    "Resived From Diary": 0,
                    "Leakage" : 0,
                    "Returned" : 0,
                    "Net Recived" : 0
                },
                "std250":{
                    "Resived From Diary": 0,
                    "Leakage" : 0,
                    "Returned" : 0,
                    "Net Recived" : 0
                },
                "fcm":{
                    "Resived From Diary": 0,
                    "Leakage" : 0,
                    "Returned" : 0,
                    "Net Recived" : 0
                },
            },
            "union_sale" : {},
            "Coimbatore Account" : {
                "Agent Cash":{
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total":0
                },
                "Agent Card" : {
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total":0
                },
                "Union Booth Cash" : {
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total":0
                },
                "Union Booth Card" : {
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total":0
                },
                "Pvt Institutes" : {
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total":0
                },
                "Govt Institutes" : {
                    "tm" : 0,
                    "std500" : 0,
                    "std250" : 0,
                    "fcm" : 0,
                    "total": 0
                },
                "Society" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
                },
                "Can Milk Buyer" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
                },
                "Kerala" : {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
                },
            }
        }
    }
    tm_std_fcm_diary_sale_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list)
    tm_std_fcm_sale_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to__in = ["Agent","ICustomer"])
    tm_std_fcm_leake_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to="Leakage").exclude(union="TIRUPPUR Union")
    tm_std_fcm_trp_leake_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to="Leakage",union="TIRUPPUR Union")

    #dairy sale (icus + agent + leakage)
    # for can
    tm_can = tm_std_fcm_diary_sale_obj.aggregate(Sum('tmcan_litre'))['tmcan_litre__sum']
    std_can = tm_std_fcm_diary_sale_obj.aggregate(Sum('smcan_litre'))["smcan_litre__sum"]
    fcm_can = tm_std_fcm_diary_sale_obj.aggregate(Sum('fcmcan_litre'))["fcmcan_litre__sum"]
    if tm_can is None:
        tm_can = 0
    if std_can is None:
        std_can = 0
    if fcm_can is None:
        fcm_can = 0

    #for milk

    tm_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum'] 
    std500_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"] 
    std250_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    fcm_sale_500 = tm_std_fcm_diary_sale_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    fcm_sale_1000 = tm_std_fcm_diary_sale_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if tm_sale is None:
        tm_sale = 0
    if std500_sale is None:
        std500_sale = 0
    if std250_sale is None:
        std250_sale = 0
    if fcm_sale_500 is None:
        fcm_sale_500 = 0
    if fcm_sale_1000 is None:
        fcm_sale_1000 = 0

    fcm_sale = fcm_sale_500 + fcm_sale_1000 

    data_dict["product"]["tm"]["Resived From Diary"] = tm_sale + tm_can
    data_dict["product"]["std500"]["Resived From Diary"] = std500_sale + std_can
    data_dict["product"]["std250"]["Resived From Diary"] = std250_sale
    data_dict["product"]["fcm"]["Resived From Diary"] = fcm_sale + fcm_can

    #net_recived (icus + agent)
    tm_can = tm_std_fcm_sale_obj.aggregate(Sum('tmcan_litre'))['tmcan_litre__sum']
    std_can = tm_std_fcm_sale_obj.aggregate(Sum('smcan_litre'))["smcan_litre__sum"]
    fcm_can = tm_std_fcm_sale_obj.aggregate(Sum('fcmcan_litre'))["fcmcan_litre__sum"]
    if tm_can is None:
        tm_can = 0
    if std_can is None:
        std_can = 0
    if fcm_can is None:
        fcm_can = 0

    tm_sale = tm_std_fcm_sale_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum'] 
    std500_sale = tm_std_fcm_sale_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"] 
    std250_sale = tm_std_fcm_sale_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    fcm_sale_500 = tm_std_fcm_sale_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    fcm_sale_1000 = tm_std_fcm_sale_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if tm_sale is None:
        tm_sale = 0
    if std500_sale is None:
        std500_sale = 0
    if std250_sale is None:
        std250_sale = 0
    if fcm_sale_500 is None:
        fcm_sale_500 = 0
    if fcm_sale_1000 is None:
        fcm_sale_1000 = 0

    tm_sale = tm_sale + tm_can
    std500_sale = std500_sale + std_can

    fcm_sale = fcm_sale_500 + fcm_sale_1000 + fcm_can

    data_dict["product"]["tm"]["Net Recived"] = tm_sale
    data_dict["product"]["std500"]["Net Recived"] = std500_sale
    data_dict["product"]["std250"]["Net Recived"] = std250_sale
    data_dict["product"]["fcm"]["Net Recived"] = fcm_sale

    #Tiruppur leakage
    trp_lk_tm_sale = tm_std_fcm_trp_leake_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    trp_lk_std500_sale = tm_std_fcm_trp_leake_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    trp_lk_std250_sale = tm_std_fcm_trp_leake_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]

    trp_lk_fcm_sale_500 = tm_std_fcm_trp_leake_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    trp_lk_fcm_sale_1000 = tm_std_fcm_trp_leake_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]


    if trp_lk_tm_sale is None:
        trp_lk_tm_sale = 0
    if trp_lk_std500_sale is None:
        trp_lk_std500_sale = 0
    if trp_lk_std250_sale is None:
        trp_lk_std250_sale = 0
    if trp_lk_fcm_sale_500 is None:
        trp_lk_fcm_sale_500 = 0
    if trp_lk_fcm_sale_1000 is None:
        trp_lk_fcm_sale_1000 = 0

    trp_lk_fcm_sale = trp_lk_fcm_sale_500 + trp_lk_fcm_sale_1000

    data_dict["product"]["tm"]["TIRUPPUR Leakage"] = trp_lk_tm_sale
    data_dict["product"]["std500"]["TIRUPPUR Leakage"] = trp_lk_std500_sale
    data_dict["product"]["std250"]["TIRUPPUR Leakage"] = trp_lk_std250_sale
    data_dict["product"]["fcm"]["TIRUPPUR Leakage"] = trp_lk_fcm_sale

    #leakage
    lk_tm_sale = tm_std_fcm_leake_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    lk_std500_sale = tm_std_fcm_leake_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    lk_std250_sale = tm_std_fcm_leake_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    lk_fcm_sale_500 = tm_std_fcm_leake_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    lk_fcm_sale_1000 = tm_std_fcm_leake_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if lk_tm_sale is None:
        lk_tm_sale = 0
    if lk_std500_sale is None:
        lk_std500_sale = 0
    if lk_std250_sale is None:
        lk_std250_sale = 0
    if lk_fcm_sale_500 is None:
        lk_fcm_sale_500 = 0
    if lk_fcm_sale_1000 is None:
        lk_fcm_sale_1000 = 0

    lk_fcm_sale = lk_fcm_sale_500 + lk_fcm_sale_1000

    data_dict["product"]["tm"]["Leakage"] = lk_tm_sale
    data_dict["product"]["std500"]["Leakage"] = lk_std500_sale
    data_dict["product"]["std250"]["Leakage"] = lk_std250_sale
    data_dict["product"]["fcm"]["Leakage"] = lk_fcm_sale

    union_list = ["COIMBATORE Union","NILGIRIS Union","TIRUPPUR Union","CHENNAI Aavin"]

    for union in union_list:
        if not union in data_dict["union_sale"]:
            data_dict["union_sale"][union] = {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0
            }
        tm_std_fcm_union_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union=union,sold_to__in = ["Agent","ICustomer"])

        # union sale
        if tm_std_fcm_union_obj:
            union_tm_sale = tm_std_fcm_union_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
            union_std500_sale = tm_std_fcm_union_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
            union_std250_sale = tm_std_fcm_union_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
            union_fcm_sale = tm_std_fcm_union_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] + tm_std_fcm_union_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

            data_dict["union_sale"][union]["tm"] = union_tm_sale
            data_dict["union_sale"][union]["std500"] = union_std500_sale
            data_dict["union_sale"][union]["std250"] = union_std250_sale
            data_dict["union_sale"][union]["fcm"] = union_fcm_sale

            data_dict["union_sale"][union]["total"] = union_tm_sale + union_std500_sale + union_std250_sale + union_fcm_sale

    #1.Agent + Pvt Parlour (cash)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "Agent",business_type_id__in=[1,2])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Agent Cash"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Agent Cash"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Agent Cash"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Agent Cash"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Agent Cash"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #2.Agent + Pvt Parlour (card)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "ICustomer",business_type_id__in=[1,2])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Agent Card"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Agent Card"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Agent Card"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Agent Card"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Agent Card"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #3.Ownparlour (cash)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "Agent",business_type_id=3)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Union Booth Cash"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Union Booth Cash"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Union Booth Cash"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Union Booth Cash"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Union Booth Cash"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #4.Ownparlour (card)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "ICustomer",business_type_id=3)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Union Booth Card"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Union Booth Card"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Union Booth Card"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Union Booth Card"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Union Booth Card"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #5.Private ins
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent","ICustomer"],business_type_id__in=[15, 4])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Pvt Institutes"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Pvt Institutes"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Pvt Institutes"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Pvt Institutes"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Pvt Institutes"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #6.Govt. ins
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent","ICustomer"],business_type_id=5)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] 
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Coimbatore Account"]["Govt Institutes"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Govt Institutes"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Govt Institutes"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Govt Institutes"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Govt Institutes"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #7.Society
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent"],business_type_id=10)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    if cbe_tm_sale == None:
        cbe_tm_sale = 0
    if cbe_std500_sale == None:
        cbe_std500_sale = 0
    if cbe_std250_sale == None:
        cbe_std250_sale = 0
    cbe_fcm_sale = 0
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"]
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    data_dict["Coimbatore Account"]["Society"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Society"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Society"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Society"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Society"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #7.Kerala
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent"],business_type_id=12)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_litre'))['tm500_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_litre'))["std500_litre__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_litre'))["std250_litre__sum"]
    if cbe_tm_sale == None:
        cbe_tm_sale = 0
    if cbe_std500_sale == None:
        cbe_std500_sale = 0
    if cbe_std250_sale == None:
        cbe_std250_sale = 0
    cbe_fcm_sale = 0
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_litre'))["fcm500_litre__sum"]
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_litre'))["fcm1000_litre__sum"]

    data_dict["Coimbatore Account"]["Kerala"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Kerala"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Kerala"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Kerala"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Kerala"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #8.Can Milk Buyer
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to__in = ["Agent","ICustomer"])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tmcan_litre'))['tmcan_litre__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('smcan_litre'))["smcan_litre__sum"]
    cbe_std250_sale = 0
    cbe_fcm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('fcmcan_litre'))["fcmcan_litre__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_fcm_sale is None:
        cbe_fcm_sale = 0

    data_dict["Coimbatore Account"]["Can Milk Buyer"]["tm"] = cbe_tm_sale
    data_dict["Coimbatore Account"]["Can Milk Buyer"]["std500"] = cbe_std500_sale
    data_dict["Coimbatore Account"]["Can Milk Buyer"]["std250"] = cbe_std250_sale
    data_dict["Coimbatore Account"]["Can Milk Buyer"]["fcm"] = cbe_fcm_sale
    data_dict["Coimbatore Account"]["Can Milk Buyer"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #-----------------------------Cost---------------------#

    tm_std_fcm_diary_sale_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list)
    tm_std_fcm_sale_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to__in = ["Agent","ICustomer"])
    tm_std_fcm_leake_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to="Leakage")

    #dairy sale (icus + agent + leakage)

    tm_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    std500_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    std250_sale = tm_std_fcm_diary_sale_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    fcm_sale_500 = tm_std_fcm_diary_sale_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] 
    fcm_sale_1000 = tm_std_fcm_diary_sale_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if tm_sale is None:
        tm_sale = 0
    if std500_sale is None:
        std500_sale = 0
    if std250_sale is None:
        std250_sale = 0
    if fcm_sale_500 is None:
        fcm_sale_500 = 0
    if fcm_sale_1000 is None:
        fcm_sale_1000 = 0

    fcm_sale = fcm_sale_1000 + fcm_sale_500

    data_dict["Costs"]["product"]["tm"]["Resived From Diary"] = tm_sale
    data_dict["Costs"]["product"]["std500"]["Resived From Diary"] = std500_sale
    data_dict["Costs"]["product"]["std250"]["Resived From Diary"] = std250_sale
    data_dict["Costs"]["product"]["fcm"]["Resived From Diary"] = fcm_sale

    #net_recived (icus + agent)
    tm_sale = tm_std_fcm_sale_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    std500_sale = tm_std_fcm_sale_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    std250_sale = tm_std_fcm_sale_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    fcm_sale_500 = tm_std_fcm_sale_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] 
    fcm_sale_1000 = tm_std_fcm_sale_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if tm_sale is None:
        tm_sale = 0
    if std500_sale is None:
        std500_sale = 0
    if std250_sale is None:
        std250_sale = 0
    if fcm_sale_500 is None:
        fcm_sale_500 = 0
    if fcm_sale_1000 is None:
        fcm_sale_1000 = 0

    fcm_sale = fcm_sale_1000 + fcm_sale_500

    data_dict["Costs"]["product"]["tm"]["Net Recived"] = tm_sale
    data_dict["Costs"]["product"]["std500"]["Net Recived"] = std500_sale
    data_dict["Costs"]["product"]["std250"]["Net Recived"] = std250_sale
    data_dict["Costs"]["product"]["fcm"]["Net Recived"] = fcm_sale

    #leakage
    lk_tm_sale = tm_std_fcm_leake_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    lk_std500_sale = tm_std_fcm_leake_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    lk_std250_sale = tm_std_fcm_leake_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    lk_fcm_sale_500 = tm_std_fcm_leake_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    lk_fcm_sale_1000 = tm_std_fcm_leake_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if lk_tm_sale is None:
        lk_tm_sale = 0
    if lk_std500_sale is None:
        lk_std500_sale = 0
    if lk_std250_sale is None:
        lk_std250_sale = 0
    if lk_fcm_sale_500 is None:
        lk_fcm_sale_500 = 0
    if lk_fcm_sale_1000 is None:
        lk_fcm_sale_1000 = 0

    lk_fcm_sale = lk_fcm_sale_500 + lk_fcm_sale_1000

    data_dict["Costs"]["product"]["tm"]["Leakage"] = lk_tm_sale
    data_dict["Costs"]["product"]["std500"]["Leakage"] = lk_std500_sale
    data_dict["Costs"]["product"]["std250"]["Leakage"] = lk_std250_sale
    data_dict["Costs"]["product"]["fcm"]["Leakage"] = lk_fcm_sale

    union_list = ["COIMBATORE Union","NILGIRIS Union","TIRUPPUR Union","CHENNAI Aavin"]

    for union in union_list:
        if not union in data_dict["Costs"]["union_sale"]:
            data_dict["Costs"]["union_sale"][union] = {
                "tm" : 0,
                "std500" : 0,
                "std250" : 0,
                "fcm" : 0,
                "total":0,
            }
        tm_std_fcm_union_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union=union,sold_to__in = ["Agent","ICustomer"])

        if tm_std_fcm_union_obj:
            # union sale
            union_tm_sale = tm_std_fcm_union_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
            union_std500_sale = tm_std_fcm_union_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
            union_std250_sale = tm_std_fcm_union_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
            union_fcm_sale = tm_std_fcm_union_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] + tm_std_fcm_union_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

            data_dict["Costs"]["union_sale"][union]["tm"] = union_tm_sale
            data_dict["Costs"]["union_sale"][union]["std500"] = union_std500_sale
            data_dict["Costs"]["union_sale"][union]["std250"] = union_std250_sale
            data_dict["Costs"]["union_sale"][union]["fcm"] = union_fcm_sale
            data_dict["Costs"]["union_sale"][union]["total"] = union_tm_sale + union_std500_sale + union_std250_sale + union_fcm_sale

    #1.Agent + Pvt Parlour (cash)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "Agent",business_type_id__in=[1,2])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Agent Cash"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Cash"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Cash"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Cash"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Cash"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #2.Agent + Pvt Parlour (card)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "ICustomer",business_type_id__in=[1,2])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Agent Card"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Card"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Card"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Card"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Agent Card"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #3.Ownparlour (cash)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "Agent",business_type_id=3)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Union Booth Cash"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Cash"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Cash"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Cash"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Cash"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #4.Ownparlour (card)
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to = "ICustomer",business_type_id=3)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Union Booth Card"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Card"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Card"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Card"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Union Booth Card"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #5.Private ins
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent","ICustomer"],business_type_id__in=[15, 4])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Pvt Institutes"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Pvt Institutes"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Pvt Institutes"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Pvt Institutes"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Pvt Institutes"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #6.Govt. ins
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent","ICustomer"],business_type_id=5)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    cbe_fcm_sale_500 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    cbe_fcm_sale_1000 = tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_std250_sale is None:
        cbe_std250_sale = 0
    if cbe_fcm_sale_500 is None:
        cbe_fcm_sale_500 = 0
    if cbe_fcm_sale_1000 is None:
        cbe_fcm_sale_1000 = 0

    cbe_fcm_sale = cbe_fcm_sale_500 + cbe_fcm_sale_1000

    data_dict["Costs"]["Coimbatore Account"]["Govt Institutes"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Govt Institutes"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Govt Institutes"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Govt Institutes"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Govt Institutes"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #6.Society
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent","ICustomer"],business_type_id=10)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    # cbe_fcm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] + tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale == None:
        cbe_tm_sale = 0
    if cbe_std500_sale == None:
        cbe_std500_sale = 0
    if cbe_std250_sale == None:
        cbe_std250_sale = 0
    cbe_fcm_sale = 0
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    data_dict["Costs"]["Coimbatore Account"]["Society"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Society"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Society"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Society"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Society"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #7.Kerala
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,union="COIMBATORE Union",sold_to__in = ["Agent"],business_type_id=12)

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tm500_cost'))['tm500_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std500_cost'))["std500_cost__sum"]
    cbe_std250_sale = tm_std_fcm_cbe_obj.aggregate(Sum('std250_cost'))["std250_cost__sum"]
    # cbe_fcm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] + tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    if cbe_tm_sale == None:
        cbe_tm_sale = 0
    if cbe_std500_sale == None:
        cbe_std500_sale = 0
    if cbe_std250_sale == None:
        cbe_std250_sale = 0
    cbe_fcm_sale = 0
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm500_cost'))["fcm500_cost__sum"]
    if tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"] != None:
        cbe_fcm_sale += tm_std_fcm_cbe_obj.aggregate(Sum('fcm1000_cost'))["fcm1000_cost__sum"]

    data_dict["Costs"]["Coimbatore Account"]["Kerala"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Kerala"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Kerala"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Kerala"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Kerala"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    #8.Can Milk Buyer
    tm_std_fcm_cbe_obj = DailySessionllyBusinessllySale.objects.filter(delivery_date__in=date_list,sold_to__in = ["Agent","ICustomer"])

    # union sale
    cbe_tm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('tmcan_cost'))['tmcan_cost__sum']
    cbe_std500_sale = tm_std_fcm_cbe_obj.aggregate(Sum('smcan_cost'))["smcan_cost__sum"]
    cbe_std250_sale = 0
    cbe_fcm_sale = tm_std_fcm_cbe_obj.aggregate(Sum('fcmcan_cost'))["fcmcan_cost__sum"]

    if cbe_tm_sale is None:
        cbe_tm_sale = 0
    if cbe_std500_sale is None:
        cbe_std500_sale = 0
    if cbe_fcm_sale is None:
        cbe_fcm_sale = 0


    data_dict["Costs"]["Coimbatore Account"]["Can Milk Buyer"]["tm"] = cbe_tm_sale
    data_dict["Costs"]["Coimbatore Account"]["Can Milk Buyer"]["std500"] = cbe_std500_sale
    data_dict["Costs"]["Coimbatore Account"]["Can Milk Buyer"]["std250"] = cbe_std250_sale
    data_dict["Costs"]["Coimbatore Account"]["Can Milk Buyer"]["fcm"] = cbe_fcm_sale
    data_dict["Costs"]["Coimbatore Account"]["Can Milk Buyer"]["total"] = cbe_tm_sale + cbe_std500_sale + cbe_std250_sale + cbe_fcm_sale

    data = create_canvas_for_total_milk_sale(data_dict, date_list)

In [108]:
def create_canvas_for_total_milk_sale(data_dict,date_list):
    file_name = "Total_milk_sale_for" + '_(' + str(date_list[0])[:10] + ' to '+str(date_list[-1])[:10] + ')' + '.pdf'
    #     file_path = os.path.join('static/media/zone_wise_report/', file_name)

    file_path = os.path.join('static/media/zone_wise_report', file_name)
#     file_path = os.path.join('static/media/', file_name)

    mycanvas = canvas.Canvas(file_path, pagesize=A4)
#     pdfmetrics.registerFont(TTFont('Helvetica', 'matrix.ttf'))
    light_color = 0x000000
    dark_color = 0x000000

    mycanvas.setFillColor(HexColor(dark_color))
    mycanvas.setFont('Helvetica', 12.5)
    mycanvas.drawCentredString(300, 820,'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')
    mycanvas.setFont('Helvetica', 13)

    #Date
    from_date = datetime.strptime(str(date_list[0])[:10], '%Y-%m-%d')
    to_date = datetime.strptime(str(date_list[-1])[:10], '%Y-%m-%d')
    mycanvas.drawCentredString(300, 800, "Sale For DATE : " + str(datetime.strftime(from_date, '%d/%m/%Y'))+" to "+str(datetime.strftime(to_date, '%d/%m/%Y')))


    mycanvas.drawCentredString(300,780, "Total Milk Sale Liters")
#     mycanvas.setDash(6,3)
    mycanvas.setLineWidth(0)
    mycanvas.line(406-100-50, 777, 593-200-50, 777)


    # Diary Sale
    x_a4 = 60
    mycanvas.setFont('Helvetica', 10)
    y_axis_head = 680+40+20

    mycanvas.drawCentredString(100-x_a4, y_axis_head, "S.NO")
    mycanvas.drawCentredString(152-x_a4, y_axis_head, "Total MIlk Sale")
    mycanvas.drawCentredString(220-x_a4, y_axis_head, "TM")
    mycanvas.drawCentredString(350-x_a4, y_axis_head+8, "STD")
    mycanvas.drawCentredString(305-x_a4, y_axis_head-5, "500")
    mycanvas.drawCentredString(395-x_a4, y_axis_head-5, "250")
    mycanvas.drawCentredString(470-x_a4, y_axis_head, "FCM")
    mycanvas.drawCentredString(535-x_a4, y_axis_head, "TOTAL")
    mycanvas.drawCentredString(610-x_a4, y_axis_head, "G-TOTAL")

    y_axis_line = 698+20+20+20
    y_axis = 645+20+20+30
    x_axis_line = 65-x_a4
    x_axis = 70-x_a4
    
    mycanvas.setFont('Helvetica', 7)
    mycanvas.line(x_axis_line+20, y_axis_line, x_axis_line + 585, y_axis_line)
    mycanvas.line(x_axis_line+20, y_axis_line-25, x_axis_line + 585, y_axis_line-25)

    sl_no = 1
    for diary in data_dict["product"]['tm']:
        if diary == 'Net Recived':
            y_axis -= 5
        if diary != 'Net Recived':
            mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
            sl_no += 1
        mycanvas.setFont('Helvetica', 7)
        mycanvas.drawString(x_axis+50, y_axis, str(diary))
        mycanvas.setFont('Helvetica', 8)
        mycanvas.drawRightString(x_axis+190, y_axis, str(data_dict["product"]["tm"][diary]))
        mycanvas.drawRightString(x_axis+270, y_axis, str(data_dict["product"]['std500'][diary]))
        mycanvas.drawRightString(x_axis+345, y_axis, str(data_dict["product"]['std250'][diary]))
        mycanvas.drawRightString(x_axis+415, y_axis, str(data_dict["product"]["fcm"][diary]))
        total = data_dict["product"]["tm"][diary] + data_dict["product"]['std500'][diary] + data_dict["product"]['std250'][diary] + data_dict["product"]["fcm"][diary]
        mycanvas.drawRightString(x_axis+495, y_axis, str(total))
        y_axis -= 20
       

    #lines

    mycanvas.line(x_axis_line+20, y_axis+37, x_axis_line + 505, y_axis+37)
    mycanvas.line(x_axis_line+20, y_axis+15, x_axis_line + 505, y_axis+15)
#     mycanvas.line(x_axis_line+50, y_axis+20, x_axis_line + 585, y_axis+20)

    mycanvas.line(x_axis_line+20, y_axis_line, x_axis_line+20, y_axis+37)
    mycanvas.line(x_axis_line+50, y_axis_line, x_axis_line+50, y_axis+20-5)
    
    mycanvas.line(x_axis_line+125, y_axis_line, x_axis_line+125, y_axis+20-5)
    mycanvas.line(x_axis_line+205, y_axis_line, x_axis_line+205, y_axis+20-5)
    mycanvas.line(x_axis_line+285, y_axis_line-13, x_axis_line+285, y_axis+20-5)
    mycanvas.line(x_axis_line+205, y_axis_line-13, x_axis_line+360,y_axis_line-13)

    mycanvas.line(x_axis_line + 360, y_axis_line, x_axis_line + 360, y_axis+20-5)
    mycanvas.line(x_axis_line + 430, y_axis_line, x_axis_line + 430, y_axis+20-5)
    mycanvas.line(x_axis_line + 505, y_axis_line, x_axis_line + 505, y_axis+20-5)
    mycanvas.line(x_axis_line + 585, y_axis_line, x_axis_line + 585, y_axis+20-5)
   
   
   
    # union_sale

    y_axis_line = y_axis +20
    y_axis = y_axis
    x_axis_line = 65-x_a4
    x_axis = 70-x_a4

#     mycanvas.line(x_axis_line+20, y_axis_line-25, x_axis_line + 585, y_axis_line-25)
#
    tm_tot = 0
    sm500_tot = 0
    sm250_tot = 0
    fcm_tot = 0
    total = 0
    for union in data_dict["union_sale"]:
        if union == 'COIMBATORE Union' or union =='NILGIRIS Union':
            pass
        else:
            tm_tot += data_dict["union_sale"][union]["tm"]
            sm500_tot += data_dict["union_sale"][union]['std500']
            sm250_tot += data_dict["union_sale"][union]['std250']
            fcm_tot += data_dict["union_sale"][union]["fcm"]
            total += data_dict["union_sale"][union]["total"]

            if data_dict["union_sale"][union]["total"] == 0:
                pass
            else:             
                mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
                mycanvas.setFont('Helvetica', 7)
                mycanvas.drawString(x_axis+50, y_axis, str(union))
                mycanvas.setFont('Helvetica', 8)
                mycanvas.drawRightString(x_axis+190, y_axis, str(data_dict["union_sale"][union]["tm"]))
                mycanvas.drawRightString(x_axis+270, y_axis, str(data_dict["union_sale"][union]['std500']))
                mycanvas.drawRightString(x_axis+345, y_axis, str(data_dict["union_sale"][union]['std250']))
                mycanvas.drawRightString(x_axis+415, y_axis, str(data_dict["union_sale"][union]["fcm"]))
                mycanvas.drawRightString(x_axis+495, y_axis, str(data_dict["union_sale"][union]["total"]))

                y_axis -= 20
                sl_no += 1

    #lines
    mycanvas.line(x_axis_line+20, y_axis+20-5, x_axis_line + 505, y_axis+20-5)

    mycanvas.line(x_axis_line+20, y_axis_line-5, x_axis_line+20, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis_line, x_axis_line+50, y_axis+20-5)
    
    mycanvas.line(x_axis_line+125, y_axis_line, x_axis_line+125, y_axis+20-5)
    mycanvas.line(x_axis_line+205, y_axis_line, x_axis_line+205, y_axis+20-5)
    mycanvas.line(x_axis_line+285, y_axis_line, x_axis_line+285, y_axis+20-5)
    mycanvas.line(x_axis_line+360, y_axis_line, x_axis_line+360, y_axis+20-5)

    mycanvas.line(x_axis_line + 430, y_axis_line, x_axis_line + 430, y_axis+20-5)
    mycanvas.line(x_axis_line + 505, y_axis_line, x_axis_line + 505, y_axis+20-5)
    mycanvas.line(x_axis_line + 585, y_axis_line, x_axis_line + 585, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis-10, x_axis_line + 505, y_axis-10)

    #     mycanvas.line(x_axis_line+50, y_axis-7, x_axis_line + 585, y_axis-7)
    
    mycanvas.drawString(x_axis+50, y_axis+3-5, "Other Union Total")
    
    mycanvas.drawString(x_axis+50, y_axis+3-25, "CBE Union Total")
    
    mycanvas.drawRightString(x_axis+190, y_axis+3-5, str(tm_tot))
    mycanvas.drawRightString(x_axis+270, y_axis+3-5, str(sm500_tot))
    mycanvas.drawRightString(x_axis+345, y_axis+3-5, str(sm250_tot))
    mycanvas.drawRightString(x_axis+415, y_axis+3-5, str(fcm_tot))
    mycanvas.drawRightString(x_axis+495, y_axis+3-5, str(total))

    
    y_axis -= 20
    mycanvas.line(x_axis_line+20, y_axis-10, x_axis_line + 505, y_axis-10)
    # Coimbatore union account

    y_axis_line = y_axis+15
    y_axis = y_axis-25
    x_axis_line = 65-x_a4
    x_axis = 70-x_a4

    cbe_tm_tot = 0
    cbe_sm250_tot = 0
    cbe_sm500_tot = 0
    cbe_fcm_tot = 0
    cbe_total = 0
    for sale in data_dict["Coimbatore Account"]:
        print(sale)

        cbe_tm_tot += data_dict["Coimbatore Account"][sale]["tm"]
        cbe_sm500_tot += data_dict["Coimbatore Account"][sale]['std500']
        cbe_sm250_tot += data_dict["Coimbatore Account"][sale]['std250']
        cbe_fcm_tot += data_dict["Coimbatore Account"][sale]["fcm"]
        cbe_total += data_dict["Coimbatore Account"][sale]["total"]

        if data_dict["Coimbatore Account"][sale]["total"] == 0:
            pass
        else:
            mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
            mycanvas.drawString(x_axis+50, y_axis, str(sale))
            mycanvas.drawRightString(x_axis+190, y_axis, str(data_dict["Coimbatore Account"][sale]["tm"]))
            mycanvas.drawRightString(x_axis+270, y_axis, str(data_dict["Coimbatore Account"][sale]['std500']))
            mycanvas.drawRightString(x_axis+345, y_axis, str(data_dict["Coimbatore Account"][sale]['std250']))
            mycanvas.drawRightString(x_axis+415, y_axis, str(data_dict["Coimbatore Account"][sale]["fcm"]))
            mycanvas.drawRightString(x_axis+495, y_axis, str(data_dict["Coimbatore Account"][sale]["total"]))

            y_axis -= 20
            sl_no += 1

    cbe_tm_tot += data_dict["union_sale"]["NILGIRIS Union"]["tm"]
    cbe_sm500_tot += data_dict["union_sale"]["NILGIRIS Union"]['std500']
    cbe_sm250_tot += data_dict["union_sale"]["NILGIRIS Union"]['std250']
    cbe_fcm_tot += data_dict["union_sale"]["NILGIRIS Union"]["fcm"]
    cbe_total += data_dict["union_sale"]["NILGIRIS Union"]["total"]

    if data_dict["union_sale"]["NILGIRIS Union"]["total"] == 0 :
        pass
    else:
        mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
        mycanvas.drawString(x_axis+50, y_axis, str("NILGIRIS Union"))
        mycanvas.drawRightString(x_axis+190, y_axis, str(data_dict["union_sale"]["NILGIRIS Union"]["tm"]))
        mycanvas.drawRightString(x_axis+270, y_axis, str(data_dict["union_sale"]["NILGIRIS Union"]['std500']))
        mycanvas.drawRightString(x_axis+345, y_axis, str(data_dict["union_sale"]["NILGIRIS Union"]['std250']))
        mycanvas.drawRightString(x_axis+415, y_axis, str(data_dict["union_sale"]["NILGIRIS Union"]["fcm"]))
        mycanvas.drawRightString(x_axis+495, y_axis, str(data_dict["union_sale"]["NILGIRIS Union"]["total"]))
        y_axis -= 20
    #lines

    mycanvas.line(x_axis_line+20, y_axis+20-5, x_axis_line + 585, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis+20-30, x_axis_line+585, y_axis+20-30)

    mycanvas.line(x_axis_line+20, y_axis_line-25, x_axis_line+20, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis_line+30, x_axis_line+50, y_axis+20-30)
    
    mycanvas.line(x_axis_line+125, y_axis_line+30, x_axis_line+125, y_axis+20-30)
    mycanvas.line(x_axis_line+205, y_axis_line+30, x_axis_line+205, y_axis+20-30)
    mycanvas.line(x_axis_line+285, y_axis_line+30, x_axis_line+285, y_axis+20-30)

    mycanvas.line(x_axis_line + 360, y_axis_line+30, x_axis_line + 360, y_axis+20-30)
    mycanvas.line(x_axis_line + 430, y_axis_line+30, x_axis_line + 430, y_axis+20-30)
    mycanvas.line(x_axis_line + 505, y_axis_line+30, x_axis_line + 505, y_axis+20-30)
    mycanvas.line(x_axis_line + 585, y_axis_line+30, x_axis_line + 585, y_axis+20-30)

    mycanvas.drawString(x_axis+50, y_axis+3-5, "CBE Union Total")
    mycanvas.drawRightString(x_axis+190, y_axis+3-5, str(cbe_tm_tot))
    mycanvas.drawRightString(x_axis+270, y_axis+3-5, str(cbe_sm500_tot))
    mycanvas.drawRightString(x_axis+345, y_axis+3-5, str(cbe_sm250_tot))
    mycanvas.drawRightString(x_axis+415, y_axis+3-5, str(cbe_fcm_tot))
    mycanvas.drawRightString(x_axis+495, y_axis+3-5, str(cbe_total))
    
    
    net_total = data_dict["product"]["tm"]['Net Recived'] + data_dict["product"]['std500']['Net Recived'] + data_dict["product"]['std250']['Net Recived'] + data_dict["product"]["fcm"]['Net Recived']
    
    mycanvas.drawRightString(x_axis+190, 565, str(data_dict["product"]["tm"]['Net Recived']- tm_tot))
    mycanvas.drawRightString(x_axis+270, 565, str(data_dict["product"]['std500']['Net Recived']- sm500_tot))
    mycanvas.drawRightString(x_axis+345, 565, str(data_dict["product"]['std250']['Net Recived']- sm250_tot))
    mycanvas.drawRightString(x_axis+415, 565, str(data_dict["product"]["fcm"]['Net Recived']- fcm_tot))
    mycanvas.drawRightString(x_axis+495, 565, str(net_total - total))
    
    cash_total = data_dict["Coimbatore Account"]['Agent Cash']["total"] + data_dict["Coimbatore Account"]['Union Booth Cash']["total"] 
    card_total = data_dict["Coimbatore Account"]['Agent Card']["total"] + data_dict["Coimbatore Account"]['Union Booth Card']["total"]
    
    csh_crd_total = cash_total + card_total
    
    mycanvas.drawRightString(x_axis+575, 505, str(cash_total))
    mycanvas.drawRightString(x_axis+575, 485, str(card_total))
    mycanvas.drawRightString(x_axis+575, 385, str(csh_crd_total))
    
    #-----------------------------------------Cost-----------------------------------------#
    mycanvas.setFont('Helvetica', 10)

    mycanvas.drawCentredString(300, 290+4, "Total Milk Sale Amount")
#     mycanvas.setDash(6,3)
    mycanvas.setLineWidth(0)
    mycanvas.line(406-100-50, 290, 593-200-50, 290)

    y_axis_head = 300-40

    mycanvas.drawCentredString(100-x_a4, y_axis_head, "S.NO")
    mycanvas.drawCentredString(155-x_a4, y_axis_head, "Total MIlk Sale")
    mycanvas.drawCentredString(235-x_a4, y_axis_head, "TM")
    mycanvas.drawCentredString(350-x_a4, y_axis_head+8, "STD")
    mycanvas.drawCentredString(310-x_a4, y_axis_head-5, "500")
    mycanvas.drawCentredString(390-x_a4, y_axis_head-5, "250")
    mycanvas.drawCentredString(460-x_a4, y_axis_head, "FCM")
    mycanvas.drawCentredString(535-x_a4, y_axis_head, "TOTAL")
    mycanvas.drawCentredString(615-x_a4, y_axis_head, "G-TOTAL")

    y_axis_line = 398-40-50-30
    y_axis = 345-40-50-20
    x_axis_line = 65-x_a4
    x_axis = 70-x_a4

    mycanvas.line(x_axis_line+20, y_axis_line, x_axis_line + 585, y_axis_line)
    mycanvas.line(x_axis_line+20, y_axis_line-25, x_axis_line + 585, y_axis_line-25)

    sl_no = 1

    tm_tot = 0
    sm500_tot = 0
    sm250_tot = 0
    fcm_tot = 0
    total = 0
    
    cash_total = data_dict['Costs']["Coimbatore Account"]['Agent Cash']["total"]+ data_dict['Costs']["Coimbatore Account"]['Union Booth Cash']["total"]
    card_total = data_dict['Costs']["Coimbatore Account"]['Agent Card']["total"]+ data_dict['Costs']["Coimbatore Account"]['Union Booth Card']["total"]
    csh_crd_total = cash_total + card_total
    
    for sale in data_dict['Costs']["Coimbatore Account"]:

        tm_tot += data_dict['Costs']["Coimbatore Account"][sale]["tm"]
        sm500_tot += data_dict['Costs']["Coimbatore Account"][sale]['std500']
        sm250_tot += data_dict['Costs']["Coimbatore Account"][sale]['std250']
        fcm_tot += data_dict['Costs']["Coimbatore Account"][sale]["fcm"]
        total += data_dict['Costs']["Coimbatore Account"][sale]["total"]

        if data_dict['Costs']["Coimbatore Account"][sale]["total"] == 0:
            pass
        else:
            mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
            mycanvas.setFont('Helvetica', 8)
            mycanvas.drawString(x_axis+50, y_axis, str(sale))
            mycanvas.drawRightString(x_axis+190, y_axis, str(round(data_dict['Costs']["Coimbatore Account"][sale]["tm"]))+'.00')
            mycanvas.drawRightString(x_axis+270, y_axis, str(round(data_dict['Costs']["Coimbatore Account"][sale]['std500']))+'.00')
            mycanvas.drawRightString(x_axis+345, y_axis, str(round(data_dict['Costs']["Coimbatore Account"][sale]['std250']))+'.00')
            mycanvas.drawRightString(x_axis+415, y_axis, str(round(data_dict['Costs']["Coimbatore Account"][sale]["fcm"]))+'.00')
            mycanvas.drawRightString(x_axis+495, y_axis, str(round(data_dict['Costs']["Coimbatore Account"][sale]["total"]))+'.00')
            
            if sale == "Union Booth Cash":
                mycanvas.drawRightString(x_axis+570, y_axis, str(round(cash_total))+'.00')
                
            if sale == "Union Booth Card":
                mycanvas.drawRightString(x_axis+570, y_axis, str(round(card_total))+'.00')

            y_axis -= 20
            sl_no += 1

    tm_tot += data_dict['Costs']["union_sale"]["NILGIRIS Union"]["tm"]
    sm500_tot += data_dict['Costs']["union_sale"]["NILGIRIS Union"]['std500']
    sm250_tot += data_dict['Costs']["union_sale"]["NILGIRIS Union"]['std250']
    fcm_tot += data_dict['Costs']["union_sale"]["NILGIRIS Union"]["fcm"]
    total += data_dict['Costs']["union_sale"]["NILGIRIS Union"]["total"]

    if data_dict['Costs']["union_sale"]["NILGIRIS Union"]["total"] == 0:
        pass
    else:
        mycanvas.drawRightString(x_axis+40, y_axis, str(sl_no))
        mycanvas.drawString(x_axis+50, y_axis, str("NILGIRIS Union"))
        mycanvas.drawRightString(x_axis+190, y_axis, str(round(data_dict['Costs']["union_sale"]["NILGIRIS Union"]["tm"]))+'.00')
        mycanvas.drawRightString(x_axis+270, y_axis, str(round(data_dict['Costs']["union_sale"]["NILGIRIS Union"]['std500']))+'.00')
        mycanvas.drawRightString(x_axis+345, y_axis, str(round(data_dict['Costs']["union_sale"]["NILGIRIS Union"]['std250']))+'.00')
        mycanvas.drawRightString(x_axis+415, y_axis, str(round(data_dict['Costs']["union_sale"]["NILGIRIS Union"]["fcm"]))+'.00')
        mycanvas.drawRightString(x_axis+495, y_axis, str(round(data_dict['Costs']["union_sale"]["NILGIRIS Union"]["total"]))+'.00')
        y_axis -= 20
    #lines

    mycanvas.line(x_axis_line+20, y_axis+20-5, x_axis_line + 585, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis+20-30, x_axis_line + 585, y_axis+20-30)

    mycanvas.line(x_axis_line+20, y_axis_line, x_axis_line+20, y_axis+20-5)
    mycanvas.line(x_axis_line+50, y_axis_line, x_axis_line+50, y_axis+20-30)
    mycanvas.line(x_axis_line+135, y_axis_line, x_axis_line+135, y_axis+20-30)
    mycanvas.line(x_axis_line+205, y_axis_line, x_axis_line+205, y_axis+20-30)
    mycanvas.line(x_axis_line+205, y_axis_line-13, x_axis_line+360, y_axis_line-13)
    mycanvas.line(x_axis_line+285, y_axis_line-13, x_axis_line+285, y_axis+20-30)

    mycanvas.line(x_axis_line + 360, y_axis_line, x_axis_line + 360, y_axis+20-30)
    mycanvas.line(x_axis_line + 430, y_axis_line, x_axis_line + 430, y_axis+20-30)
    mycanvas.line(x_axis_line + 510, y_axis_line, x_axis_line + 510, y_axis+20-30)
    mycanvas.line(x_axis_line + 585, y_axis_line, x_axis_line + 585, y_axis+20-30)
   
    mycanvas.setFont('Helvetica', 7)
    mycanvas.drawString(x_axis+46, y_axis+3-5, "CBE Union Total Amount")
    mycanvas.setFont('Helvetica', 8)
    mycanvas.drawRightString(x_axis+190, y_axis+3-5, str(round(tm_tot)) + '.00')
    mycanvas.drawRightString(x_axis+270, y_axis+3-5, str(round(sm500_tot)) + '.00')
    mycanvas.drawRightString(x_axis+345, y_axis+3-5, str(round(sm250_tot)) + '.00')
    mycanvas.drawRightString(x_axis+415, y_axis+3-5, str(round(fcm_tot)) + '.00')
    mycanvas.drawRightString(x_axis+495, y_axis+3-5, str(round(total)) + '.00')
    mycanvas.drawRightString(x_axis+570, y_axis+3-5, str(round(csh_crd_total)) + '.00')
   
    indian = pytz.timezone('Asia/Kolkata')
#     mycanvas.setFont('Times-Italic', 10)
#     mycanvas.drawRightString(585, 5, 'Report Generated by: '+str(data_dict['user_name']+", @"+str(datetime.now().astimezone(indian).strftime("%Y-%m-%d %I:%M:%S"))))

    mycanvas.save()
    document = {}
    document['file_name'] = file_name
    try:
        image_path = file_path
        with open(image_path, 'rb') as image_file:
            encoded_image = b64encode(image_file.read())
            document['pdf'] = encoded_image
    except Exception as err:
        print(err)
    return document

In [109]:
run_pdf_script()

Agent Cash
Agent Card
Union Booth Cash
Union Booth Card
Pvt Institutes
Govt Institutes
Society
Can Milk Buyer
Kerala
name 'b64encode' is not defined

In [47]:
from_date = "2020-07-1"
to_date = "2021-03-30"
customer_type = 'Both'
bank_transaction_obj = BankTransaction.objects.filter(crtd_date__date__range=[from_date, to_date], is_rid_matched=False)

bank_transaction_list = list(bank_transaction_obj.values_list('rid', 'customer_code', 'amount', 'transaction_mode', 'clrnce_date', 'crtd_date', 'athrsd_date', 'aggregrator'))                                                 
bank_transaction_column = ['RID', 'Booth/Customr Code', 'Amount', 'Transaction Mode', 'CLRNCE DATE', 'CRTD DATE', 'ATHRSD DATE', 'Aggregrator']
bank_transaction_df = pd.DataFrame(bank_transaction_list, columns=bank_transaction_column)

if customer_type == 'Cash':
    bank_transaction_df = bank_transaction_df[bank_transaction_df['Booth/Customr Code'].str[:3]!='CBE']
elif customer_type == 'Card':
   bank_transaction_df = bank_transaction_df[bank_transaction_df['Booth/Customr Code'].str[:3]=='CBE']
else:
    bank_transaction_df = bank_transaction_df

bank_transaction_df = bank_transaction_df.reset_index(drop=True)
bank_transaction_df.index += 1

,RID,Booth/Customr Code,Amount,Transaction Mode,CLRNCE DATE,CRTD DATE,ATHRSD DATE,Aggregrator
1,2072500008,123,1.000,INTERNET BANKING,2020-07-25 12:09:52+00:00,2020-07-25 12:05:22+00:00,2020-07-25 12:05:40+00:00,0
2,2072400026,123,1.000,INTERNET BANKING,2020-07-24 18:30:40+00:00,2020-07-24 18:24:22+00:00,2020-07-24 18:24:37+00:00,0
3,2072500012,123,2.000,INTERNET BANKING,2020-07-25 13:19:49+00:00,2020-07-25 13:17:46+00:00,2020-07-25 13:17:54+00:00,0
4,2072500006,123,50.000,INTERNET BANKING,2020-07-25 11:50:05+00:00,2020-07-25 11:45:59+00:00,2020-07-25 11:46:05+00:00,ATOM
5,2072700010,189,8.000,INTERNET BANKING,2020-07-27 16:20:52+00:00,2020-07-27 16:19:19+00:00,2020-07-27 16:19:31+00:00,0
6,2072900011,2658,82.500,INTERNET BANKING,2020-07-29 08:29:51+00:00,2020-07-29 08:28:54+00:00,2020-07-29 08:29:05+00:00,0
7,20727100011,123,10.000,INTERNET BANKING,2020-07-27 13:54:41+00:00,2020-07-27 13:53:02+00:00,2020-07-27 13:53:18+00:00,0
8,2072700003,189,10.000,INTERNET BANKING,2020-07-27 15:37:35+00:00,2020-07-27 15:34:32+00:00,2020-07-27 15:34:46+00:00,ATOM
9,2082400044,CBE208764,2025.000,UPI,2020-08-24 14:18:54+00:00,2020-08-24 14:17:34+00:00,2020-08-24 14:18:54+00:00,0
10,2091400121,1875,5124.000,Credit Card/Debit card,2020-09-15 04:46:26+00:00,2020-09-15 04:43:06+00:00,2020-09-15 04:43:15+00:00,ATOM
11,20111100005,CBE427392,1860.000,Credit Card/Debit card,2020-11-11 07:13:09+00:00,2020-11-11 07:11:28+00:00,2020-11-11 07:11:50+00:00,0
12,20111600193,CBE208999,3146.500,INTERNET BANKING,2020-11-16 16:52:35+00:00,2020-11-16 16:51:31+00:00,2020-11-16 16:51:57+00:00,ATOM
13,20112400042,CBE322477,3487.500,Credit Card/Debit card,2020-11-24 09:08:10+00:00,2020-11-24 09:06:24+00:00,2020-11-24 09:08:10+00:00,0
14,2012900003,CBE202774,697.500,Credit Card/Debit card,2020-12-09 06:47:53+00:00,2020-12-09 06:42:41+00:00,2020-12-09 06:45:00+00:00,0
15,20112700214,CBE121660,6975.000,INTERNET BANKING,2020-11-27 16:56:08+00:00,2020-11-27 16:55:07+00:00,2020-11-27 16:55:21+00:00,ATOM
16,20122200077,CBE208642,1054.000,Credit Card/Debit card,2020-12-22 13:21:09+00:00,2020-12-22 13:14:37+00:00,2020-12-22 03:28:11+00:00,ATOM
17,20121000044,CBE321114,1395.000,Credit Card/Debit card,2020-12-10 12:49:07+00:00,2020-12-10 12:41:34+00:00,2020-12-10 12:42:12+00:00,ATOM
18,2012300208,CBE427392,1860.000,Credit Card/Debit card,2020-12-03 21:19:04+00:00,2020-12-03 21:15:03+00:00,2020-12-03 21:15:22+00:00,0
19,2111300193,CBE125827,2940.000,UPI,2021-01-13 18:26:55+00:00,2021-01-13 18:25:11+00:00,2021-01-13 18:26:55+00:00,0
20,211700051,CBE321390,882.000,Credit Card/Debit card,2021-01-07 11:43:53+00:00,2021-01-07 11:39:32+00:00,2021-01-07 14:00:37+00:00,0
21,2111100202,CBE311905,1120.000,UPI,2021-01-11 19:16:08+00:00,2021-01-11 19:08:28+00:00,2021-01-11 19:16:08+00:00,0
22,2122300054,CBE427559,73.500,INTERNET BANKING,2021-02-23 09:39:17+00:00,2021-02-23 09:37:04+00:00,2021-02-23 12:08:18+00:00,ATOM
23,2122200065,CBE427559,73.500,INTERNET BANKING,2021-02-22 11:30:56+00:00,2021-02-22 11:28:44+00:00,2021-02-22 12:02:28+00:00,ATOM
24,2121200294,CBE311905,1240.000,Credit Card/Debit card,2021-02-12 17:07:28+00:00,2021-02-12 17:03:28+00:00,2021-02-12 17:07:28+00:00,0
25,212600209,CBE126067,1240.000,Credit Card/Debit card,2021-02-06 16:08:19+00:00,2021-02-06 16:05:59+00:00,2021-02-06 16:08:19+00:00,0
26,2122600116,CBE427000,6975.000,INTERNET BANKING,2021-02-26 00:00:00+00:00,2021-02-26 12:54:03+00:00,2021-02-26 14:07:24+00:00,AXIS
27,2122600201,CBE312370,1240.000,UPI,2021-02-26 15:09:46+00:00,2021-02-26 15:04:18+00:00,2021-02-26 15:09:46+00:00,0
28,2122600437,CBE210505,2278.500,Credit Card/Debit card,2021-02-26 22:31:39+00:00,2021-02-26 22:29:01+00:00,2021-02-26 22:31:39+00:00,0
29,2132600368,CBE311098,1350.000,UPI,2021-03-26 21:21:02+00:00,2021-03-26 21:21:35+00:00,2021-03-26 21:21:02+00:00,0
30,2132300152,CBE427746,675.000,INTERNET BANKING,2021-03-23 14:40:50+00:00,2021-03-23 14:36:01+00:00,2021-03-23 16:04:53+00:00,ATOM
31,2072500011,123,1.000,INTERNET BANKING,2020-07-25 13:10:27+00:00,2020-07-25 13:08:25+00:00,2020-07-25 13:08:34+00:00,0
32,2072500010,123,50.000,Credit Card/Debit card,2020-07-25 12:23:44+00:00,2020-07-25 12:21:24+00:00,2020-07-25 12:21:30+00:00,ATOM

In [7]:
product_obj = ICustomerTypeWiseProductDiscount.objects.filter(customer_type_id=2,
                                                                    product__is_active=True).order_by(
    'product__display_ordinal')
product_obj_list = list(
    product_obj.values_list('product_id', 'product__group', 'product__group__name',
                            'product__name', 'product__short_name', 'product__code',
                            'product__unit',
                            'product__unit__display_name', 'product__description',
                            'product__quantity', 'discounted_price', 'product__gst_percent', 'product__color'))
product_obj_column = ['product_id', 'product_group_id', 'product_group_name', 'product_name',
                    'product_short_name',
                    'product_code', 'unit_id', 'unit_name', 'description', 'product_quantity',
                    'product_mrp',
                    'gst_percent', 'color']
product_df = pd.DataFrame(product_obj_list, columns=product_obj_column)

product_list = product_df.groupby('product_short_name').apply(lambda x: x.to_dict('r')[0]).to_dict()

In [4]:
from calendar import monthrange, month_name
date_value = datetime.now()

In [18]:
date_value.replace(day = monthrange(date_value.year, date_value.month)[1]).date()

datetime.date(2021, 5, 31)

In [5]:
import datetime
datetime.datetime.now().date().day

24

In [9]:
today = datetime.datetime.now()
from_date = today.date() + datetime.timedelta(days=1)
to_date = today.date()

In [15]:
today.date().day

24

In [12]:
to_date = today.replace(day = monthrange(today.year, today.month)[1]).date()

In [16]:
start_date = today.replace(day=1)

In [18]:
start_date.date()

datetime.date(2021, 5, 1)

In [21]:
EmployeeOrderChangeLog.objects.filter()[0].product.short_name

'STD 500'

In [6]:
month = 1
year = 2021

days = monthrange(year, month)

data_dict ={
    "Card Sales":{
        "TM 500":{
            "am":0,
            "pm":0,
            "total":0,
            "qty/day":0,
            "days":0,
            "total/qty":0,
            "rate":0,
            "total_value":0,
        },
        "STD 250":{
            "am":0,
            "pm":0,
            "total":0,
            "qty/day":0,
            "days":0,
            "total/qty":0,
            "rate":0,
            "total_value":0,
        },
        "STD 500":{
            "am":0,
            "pm":0,
            "total":0,
            "qty/day":0,
            "days":0,
            "total/qty":0,
            "rate":0,
            "total_value":0,
        },
        "FCM 500":{
            "am":0,
            "pm":0,
            "total":0,
            "qty/day":0,
            "days":0,
            "total/qty":0,
            "rate":0,
            "total_value":0,
        }
    },
    "employees":{}
}
icustomer_sale_group = ICustomerSaleGroup.objects.filter(date__month=month,date__year=year,icustomer__customer_type_id__in=[1,5])
icustomer_sale = ICustomerSale.objects.filter(icustomer_sale_group__in=icustomer_sale_group)
for sale in icustomer_sale:
    try:
        if sale.icustomer_sale_group.session_id == 1:
            data_dict["Card Sales"][sale.product.short_name]["am"] += int(sale.count)
            data_dict["Card Sales"][sale.product.short_name]["total"] += int(sale.count)
            data_dict["Card Sales"][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["Card Sales"][sale.product.short_name]["days"] = days[1]
            data_dict["Card Sales"][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["Card Sales"][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["Card Sales"][sale.product.short_name]["total_value"] += sale.cost_for_month
        else:
            data_dict["Card Sales"][sale.product.short_name]["pm"] += int(sale.count) 
            data_dict["Card Sales"][sale.product.short_name]["total"] += int(sale.count)
            data_dict["Card Sales"][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["Card Sales"][sale.product.short_name]["days"] = days[1]
            data_dict["Card Sales"][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["Card Sales"][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["Card Sales"][sale.product.short_name]["total_value"] += sale.cost_for_month
    except Exception as e:
        print(e)

icustomer_sale_group_obj = ICustomerSaleGroup.objects.filter(date__month=month,date__year=year,icustomer__customer_type_id__in=[2,3])
for union in UnionForIcustomer.objects.all():
    icustomer_sale_group = icustomer_sale_group_obj.filter(icustomer__union_for_icustomer_id=union.id)
    icustomer_sale = ICustomerSale.objects.filter(icustomer_sale_group__in=icustomer_sale_group)
    for sale in icustomer_sale.filter(icustomer_sale_group__icustomer__customer_type__id = 3):
#             if sale.icustomer_sale_group.icustomer.customer_type.id == 3:
        sub_dict = {
            "TM 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
                },
                "STD 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
        }
        if not union.short_name in data_dict["employees"]:
#                 heading_dict[union.name + sale.icustomer_sale_group.icustomer.customer_type.name] = ""
            data_dict["employees"][union.short_name] = {
                "TM 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
                },
                "STD 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
                },
            }
        if sale.icustomer_sale_group.session_id == 1:
            data_dict["employees"][union.short_name][sale.product.short_name]["am"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["employees"][union.short_name][sale.product.short_name]["days"] = days[1]
            data_dict["employees"][union.short_name][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["employees"][union.short_name][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total_value"] += sale.cost_for_month
        else:
            data_dict["employees"][union.short_name][sale.product.short_name]["pm"] += int(sale.count) 
            data_dict["employees"][union.short_name][sale.product.short_name]["total"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["employees"][union.short_name][sale.product.short_name]["days"] = days[1]
            data_dict["employees"][union.short_name][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["employees"][union.short_name][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total_value"] += sale.cost_for_month

    for sale in icustomer_sale.filter(icustomer_sale_group__icustomer__customer_type__id = 2):
        if not union.short_name in data_dict["employees"]:
#                 heading_dict[union.name + sale.icustomer_sale_group.icustomer.customer_type.name] = ""
            data_dict["employees"][union.short_name] = {
                "TM 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
                },
                "STD 500":{
                    "am":0,
                    "pm":0,
                    "total":0,
                    "qty/day":0,
                    "days":0,
                    "total/qty":0,
                    "rate":0,
                    "total_value":0,
                },
            }
        if sale.icustomer_sale_group.session_id == 1:
            data_dict["employees"][union.short_name][sale.product.short_name]["am"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["employees"][union.short_name][sale.product.short_name]["days"] = days[1]
            data_dict["employees"][union.short_name][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["employees"][union.short_name][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total_value"] += sale.cost_for_month
        else:
            data_dict["employees"][union.short_name][sale.product.short_name]["pm"] += int(sale.count) 
            data_dict["employees"][union.short_name][sale.product.short_name]["total"] += int(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["qty/day"] += Decimal(sale.count)*Decimal(sale.product.quantity)/1000
            data_dict["employees"][union.short_name][sale.product.short_name]["days"] = days[1]
            data_dict["employees"][union.short_name][sale.product.short_name]["total/qty"] += (Decimal(sale.count)*Decimal(sale.product.quantity)/1000)*Decimal(days[1])
            data_dict["employees"][union.short_name][sale.product.short_name]["rate"] = float(sale.cost)/float(sale.count)
            data_dict["employees"][union.short_name][sale.product.short_name]["total_value"] += sale.cost_for_month
data_dict

{'Card Sales': {'TM 500': {'am': 4934,
   'pm': 2,
   'total': 4936,
   'qty/day': Decimal('2468.000'),
   'days': 31,
   'total/qty': Decimal('76508.000'),
   'rate': 20.0,
   'total_value': Decimal('3060320.00')},
  'STD 250': {'am': 3194,
   'pm': 194,
   'total': 3388,
   'qty/day': Decimal('847.000'),
   'days': 31,
   'total/qty': Decimal('26257.000'),
   'rate': 11.5,
   'total_value': Decimal('1207822.00')},
  'STD 500': {'am': 19579,
   'pm': 565,
   'total': 20144,
   'qty/day': Decimal('10072.000'),
   'days': 31,
   'total/qty': Decimal('312232.000'),
   'rate': 22.5,
   'total_value': Decimal('14050440.00')},
  'FCM 500': {'am': 1181,
   'pm': 0,
   'total': 1181,
   'qty/day': Decimal('590.500'),
   'days': 31,
   'total/qty': Decimal('18305.500'),
   'rate': 24.5,
   'total_value': Decimal('896969.50')}},
 'employees': {'STAFF CARD': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 311,
    'pm': 0,
    'total': 311,
    'qty/day': Decimal('155.500'),
    'days': 31,
    'total/qty': Decimal('4820.500'),
    'rate': 22.5,
    'total_value': Decimal('216922.50')}},
  'STAFF CARD Rtd': {'TM 500': {'am': 4,
    'pm': 0,
    'total': 4,
    'qty/day': Decimal('2.000'),
    'days': 31,
    'total/qty': Decimal('62.000'),
    'rate': 20.0,
    'total_value': Decimal('2480.00')},
   'STD 500': {'am': 208,
    'pm': 0,
    'total': 208,
    'qty/day': Decimal('104.000'),
    'days': 31,
    'total/qty': Decimal('3224.000'),
    'rate': 22.5,
    'total_value': Decimal('145080.00')}},
  'SC.TCMPF': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'tcmpf Rtd.Staff': {'TM 500': {'am': 18,
    'pm': 0,
    'total': 18,
    'qty/day': Decimal('9.000'),
    'days': 31,
    'total/qty': Decimal('279.000'),
    'rate': 20.0,
    'total_value': Decimal('11160.00')},
   'STD 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 22.5,
    'total_value': Decimal('3487.50')}},
  'NJF.OOTY': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'NDCMPU': {'TM 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 20.0,
    'total_value': Decimal('3100.00')},
   'STD 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0}},
  'MDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'EDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'TPRDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}}}}

In [45]:
month = 5
year = 2021
days = monthrange(year, month)[1]

icustomer_sale_group = ICustomerSaleGroup.objects.filter(date__month=month,date__year=year,icustomer__customer_type_id__in=[1,5])

customer_list = list(icustomer_sale_group.values_list('icustomersale__count', 'icustomersale__cost', 'icustomersale__cost_for_month', 'session_id', 'icustomersale__product_id', 'icustomersale__product__short_name', 'icustomer__union_for_icustomer_id', 'icustomer__union_for_icustomer__name', 'icustomer__customer_type__id'))
customer_columns = ['count', 'cost', 'cost_for_month', 'session_id', 'product_id', 'product_name', 'customer_union_id', 'customer_union_name', 'customer_type_id']
customer_df = pd.DataFrame(customer_list, columns=customer_columns)
customer_df = customer_df.fillna('')

customer_df['customer_code'] = ''
customer_df['from_date'] = ''
customer_df['to_date'] = ''
customer_df['total_days'] = days
customer_df['am'] = ''
customer_df['pm'] = ''
customer_df = customer_df.groupby(['product_id', 'product_name', 'customer_union_id', 'customer_union_name', 'session_id', 'customer_code', 'from_date', 'to_date', 'total_days', 'am', 'pm']).agg({'count':sum, 'cost':sum, 'cost_for_month':sum}).reset_index()                                                                               

final_df = customer_df[customer_df['session_id'] == 1]
customer_eve = customer_df[customer_df['session_id'] == 2]

for index,value  in customer_eve.iterrows():
    final_df.loc[final_df['customer_union_name'] == value.customer_union_name, ['pm']] = value['count']
    final_df.loc[final_df['customer_union_name'] == value.customer_union_name, ['cost_for_month']] += value['cost_for_month']
    final_df.loc[final_df['customer_union_name'] == value.customer_union_name, ['cost']] += value['cost']

final_df['am'] = final_df['count']
final_df = final_df.drop(columns=['count', 'session_id'])

final_df.to_dict('r')

# customer_df

<ipython-input-45-490b066b8055>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['am'] = final_df['count']

[{'product_id': 1,
  'product_name': 'TM 500',
  'customer_union_id': '',
  'customer_union_name': '',
  'customer_code': '',
  'from_date': '',
  'to_date': '',
  'total_days': 31,
  'am': 5017.0,
  'pm': 109.0,
  'cost': Decimal('114298.50'),
  'cost_for_month': Decimal('3543253.50')},
 {'product_id': 2,
  'product_name': 'STD 500',
  'customer_union_id': '',
  'customer_union_name': '',
  'customer_code': '',
  'from_date': '',
  'to_date': '',
  'total_days': 31,
  'am': 19916.0,
  'pm': 109.0,
  'cost': Decimal('462068.50'),
  'cost_for_month': Decimal('14324123.50')},
 {'product_id': 3,
  'product_name': 'STD 250',
  'customer_union_id': '',
  'customer_union_name': '',
  'customer_code': '',
  'from_date': '',
  'to_date': '',
  'total_days': 31,
  'am': 4065.0,
  'pm': 109.0,
  'cost': Decimal('60706.00'),
  'cost_for_month': Decimal('1881886.00')},
 {'product_id': 4,
  'product_name': 'FCM 500',
  'customer_union_id': '',
  'customer_union_name': '',
  'customer_code': '',
  'from_date': '',
  'to_date': '',
  'total_days': 31,
  'am': 1441.0,
  'pm': 109.0,
  'cost': Decimal('49263.00'),
  'cost_for_month': Decimal('1527153.00')}]

In [14]:
month = 1
year = 2021
days = monthrange(year, month)[1]

#-------------------------------------- Datas For Customers ---------------------------------------
icustomer_sale_group = ICustomerSaleGroup.objects.filter(date__month=month,date__year=year,icustomer__customer_type_id__in=[1,5])

customer_list = list(icustomer_sale_group.values_list('icustomersale__count', 'icustomersale__cost', 'icustomersale__cost_for_month', 'session_id', 'icustomersale__product_id', 'icustomersale__product__short_name', 'icustomersale__product__quantity', 'icustomer__union_for_icustomer_id', 'icustomer__union_for_icustomer__name', 'icustomer__customer_type__id'))
customer_columns = ['count', 'cost', 'cost_for_month', 'session_id', 'product_id', 'product_name', 'product_quantity', 'customer_union_id', 'customer_union_name', 'customer_type_id']
customer_df = pd.DataFrame(customer_list, columns=customer_columns)
customer_df = customer_df.fillna('')

customer_df['customer_code'] = ''
customer_df['from_date'] = ''
customer_df['to_date'] = ''
customer_df['total_days'] = days
customer_df['am'] = ''
customer_df['pm'] = ''
customer_df = customer_df.groupby(['product_id', 'product_name', 'product_quantity', 'customer_union_id', 'customer_union_name', 'session_id', 'customer_code', 'from_date', 'to_date', 'total_days', 'am', 'pm']).agg({'count':sum, 'cost':sum, 'cost_for_month':sum}).reset_index()                                                                               

# customer_df['product_cost'] = cost

final_df = customer_df[customer_df['session_id'] == 1]
final_df = final_df.reset_index(drop=True)
final_df.index += 1

customer_eve = customer_df[customer_df['session_id'] == 2]
customer_eve = customer_eve.reset_index(drop=True)
customer_eve.index += 1

for index,value  in customer_eve.iterrows():
    print(index)
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']) , ['pm']] = value['count']
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']), ['cost_for_month']] += value['cost_for_month']
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']), ['cost']] += value['cost']

final_df['am'] = final_df['count']
final_df = final_df.fillna(0)
final_df = final_df.replace('',0)

final_df['product_cost'] = final_df['cost'].astype(float)/(final_df['am'].astype(float) + final_df['pm'].astype(float))
final_df['total_pockets_per_day'] = final_df['am'] + final_df['pm']
final_df['pockets_per_ltr'] = 1000/final_df['product_quantity'].astype(float)
final_df['total_ltrs_per_day'] = final_df['total_pockets_per_day'].astype(float) / final_df['pockets_per_ltr'].astype(float)
final_df['total_ltrs_per_month'] = final_df['total_ltrs_per_day'].astype(float) * final_df['total_days']
final_df = final_df.drop(columns=['count', 'session_id'])
card_sales_dict = final_df.to_dict('r')

#------------------------------- Datas For Employees and Ex-Employees -------------------------------

exclude_sale_list = list(EmployeeOrderChangeLog.objects.filter(date_of_delivery__month=month, date_of_delivery__year=year, employee_order_change_mode_id=2).values_list('icustomer_sale_id', flat=True))

icustomer_sale_group_obj = ICustomerSaleGroup.objects.filter(date__month=month,date__year=year,icustomer__customer_type_id__in=[2,3]).exclude(icustomersale__id__in=exclude_sale_list)

icustomer_salegroup_list = list(icustomer_sale_group_obj.values_list('icustomersale__count', 'icustomersale__cost', 'icustomersale__cost_for_month', 'session_id', 'icustomersale__product_id', 'icustomersale__product__short_name', 'icustomersale__product__quantity', 'icustomer__union_for_icustomer_id', 'icustomer__union_for_icustomer__name', 'icustomer__customer_type__id'))                              
icustomer_salegroup_columns = ['count', 'cost', 'cost_for_month', 'session_id', 'product_id', 'product_name', 'product_quantity', 'customer_union_id', 'customer_union_name', 'customer_type_id']
customer_salegroup_df = pd.DataFrame(icustomer_salegroup_list, columns=icustomer_salegroup_columns)
customer_salegroup_df['customer_code'] = ''
customer_salegroup_df['from_date'] = ''
customer_salegroup_df['to_date'] = ''
customer_salegroup_df['total_days'] = days
customer_salegroup_df['am'] = ''
customer_salegroup_df['pm'] = ''
customer_salegroup_df = customer_salegroup_df.groupby(['product_id', 'product_name', 'product_quantity', 'customer_union_id', 'customer_union_name', 'session_id', 'customer_code', 'from_date', 'to_date', 'total_days', 'am', 'pm']).agg({'count':sum, 'cost':sum, 'cost_for_month':sum}).reset_index()                                                                               
customer_salegroup_df = customer_salegroup_df.fillna(0)

final_df = customer_salegroup_df[customer_salegroup_df['session_id'] == 1]
customer_salegroup_df_eve = customer_salegroup_df[customer_salegroup_df['session_id'] == 2]

for index,value  in customer_salegroup_df_eve.iterrows():
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']), ['pm']] = value['count']
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']), ['cost_for_month']] += value['cost_for_month']
    final_df.loc[(final_df['customer_union_name'] == value['customer_union_name'])&(final_df['product_name'] == value['product_name']), ['cost']] += value['cost']

final_df['am'] = final_df['count']
final_df = final_df.fillna(0)
final_df = final_df.replace('',0)

final_df['product_cost'] = final_df['cost'].astype(float)/(final_df['am'].astype(float) + final_df['pm'].astype(float))
final_df['total_pockets_per_day'] = final_df['am'] + final_df['pm']
final_df['pockets_per_ltr'] = 1000/final_df['product_quantity'].astype(float)
final_df['total_ltrs_per_day'] = final_df['total_pockets_per_day'].astype(float) / final_df['pockets_per_ltr'].astype(float)
final_df['total_ltrs_per_month'] = final_df['total_ltrs_per_day'].astype(float) * final_df['total_days']
final_df = final_df.drop(columns=['count', 'session_id'])

#--------------------------------------- Edited Order/ New Order/ Deleted Order from employee order change log------------
employee_order_change_log_obj = EmployeeOrderChangeLog.objects.filter(date_of_delivery__month=month, date_of_delivery__year=year)
employee_order_change_list = list(employee_order_change_log_obj.values_list('total_days', 'from_date', 'to_date', 'employee_order_change_mode_id', 'employee_order_change_mode__name', 'icustomer__customer_code', 'icustomer__union_for_icustomer_id', 'icustomer__union_for_icustomer__name', 'product__short_name', 'product__quantity', 'product_id', 'cost_per_quantity', 'count', 'total_cost', 'icustomer_sale_id', 'session_id', 'time_created'))                                                               
employee_order_change_columns = ['total_days', 'from_date', 'to_date', 'mode_id', 'mode_name', 'customer_code', 'customer_union_id', 'customer_union_name', 'product_name', 'product_quantity', 'product_id', 'cost', 'count', 'cost_for_month', 'icustomer_sale_id', 'session_id', 'time_created']
employee_order_change_df = pd.DataFrame(employee_order_change_list,columns=employee_order_change_columns)
employee_order_change_df["am"] = ''
employee_order_change_df["pm"] = ''
employee_order_change_df = employee_order_change_df.fillna(0)

employee_order_change_df_mor = employee_order_change_df[employee_order_change_df['session_id'] == 1]
employee_order_change_df_eve = employee_order_change_df[employee_order_change_df['session_id'] == 2]
employee_order_change_df_mor['am'] = employee_order_change_df_mor['count']
employee_order_change_df_eve['pm'] = employee_order_change_df_eve['count']
employee_order_change_df = pd.concat([employee_order_change_df_mor, employee_order_change_df_eve], sort=True)

employee_order_change_df = employee_order_change_df.fillna(0)
employee_order_change_df = employee_order_change_df.replace('',0)

employee_order_change_df = employee_order_change_df.sort_values(by=['product_id'])

employee_order_change_df = employee_order_change_df.drop(columns=['mode_id', 'mode_name', 'count', 'session_id', 'time_created'])

employee_order_change_df['product_cost'] = employee_order_change_df['cost'].astype(float)/(employee_order_change_df['am'].astype(float) + employee_order_change_df['pm'].astype(float))

employee_order_change_df = pd.concat([final_df, employee_order_change_df], sort=True)
employee_order_change_df = employee_order_change_df.drop(columns=['icustomer_sale_id'])
employee_order_change_df = employee_order_change_df.fillna(0)

employee_order_change_df['total_pockets_per_day'] = employee_order_change_df['am'] + employee_order_change_df['pm']
employee_order_change_df['pockets_per_ltr'] = 1000/employee_order_change_df['product_quantity'].astype(float)
employee_order_change_df['total_ltrs_per_day'] = employee_order_change_df['total_pockets_per_day'].astype(float) / employee_order_change_df['pockets_per_ltr'].astype(float)
employee_order_change_df['total_ltrs_per_month'] = employee_order_change_df['total_ltrs_per_day'].astype(float) * employee_order_change_df['total_days']

final_dict = employee_order_change_df.groupby('customer_union_name').apply(lambda x: x.to_dict('r')).to_dict()

data_dict = {}
data_dict['employees'] = final_dict
data_dict['Card Sales'] = card_sales_dict

data_dict

employee_order_change_df

1
2
3

,am,cost,cost_for_month,customer_code,customer_union_id,customer_union_name,from_date,pm,pockets_per_ltr,product_cost,product_id,product_name,product_quantity,to_date,total_days,total_ltrs_per_day,total_ltrs_per_month,total_pockets_per_day
0,1.0,20.00,620.00,0,2,CBE STAFF CARD,0,0,2.0,20.0,1,TM 500,500.000,0,31,0.5,15.5,1.0
1,3.0,60.00,1860.00,0,5,CBE STAFF CARD Rtd,0,0,2.0,20.0,1,TM 500,500.000,0,31,1.5,46.5,3.0
2,18.0,360.00,11160.00,0,7,"TCMPF,RTD",0,0,2.0,20.0,1,TM 500,500.000,0,31,9.0,279.0,18.0
3,1.0,20.00,620.00,0,9,NJF.OOTY,0,0,2.0,20.0,1,TM 500,500.000,0,31,0.5,15.5,1.0
4,5.0,100.00,3100.00,0,10,NDCMPU,0,0,2.0,20.0,1,TM 500,500.000,0,31,2.5,77.5,5.0
5,311.0,6997.50,216922.50,0,2,CBE STAFF CARD,0,0,2.0,22.5,2,STD 500,500.000,0,31,155.5,4820.5,311.0
6,206.0,4635.00,143685.00,0,5,CBE STAFF CARD Rtd,0,0,2.0,22.5,2,STD 500,500.000,0,31,103.0,3193.0,206.0
7,1.0,22.50,697.50,0,6,TCMPF,0,0,2.0,22.5,2,STD 500,500.000,0,31,0.5,15.5,1.0
8,5.0,112.50,3487.50,0,7,"TCMPF,RTD",0,0,2.0,22.5,2,STD 500,500.000,0,31,2.5,77.5,5.0
9,2.0,45.00,1395.00,0,9,NJF.OOTY,0,0,2.0,22.5,2,STD 500,500.000,0,31,1.0,31.0,2.0
10,1.0,22.50,697.50,0,11,MDCMPU,0,0,2.0,22.5,2,STD 500,500.000,0,31,0.5,15.5,1.0
11,2.0,45.00,1395.00,0,12,EDCMPU,0,0,2.0,22.5,2,STD 500,500.000,0,31,1.0,31.0,2.0
12,1.0,22.50,697.50,0,13,TPRDCMPU,0,0,2.0,22.5,2,STD 500,500.000,0,31,0.5,15.5,1.0
2,1.0,20.00,560.00,EXEMP427675,5,CBE STAFF CARD Rtd,2021-01-04,0,2.0,20.0,1,TM 500,500.000,2021-01-31,28,0.5,14.0,1.0
0,1.0,22.50,180.00,CBE1120416,2,CBE STAFF CARD,2021-01-01,0,2.0,22.5,2,STD 500,500.000,2021-01-08,8,0.5,4.0,1.0
1,1.0,22.50,607.50,EXEMP427817,5,CBE STAFF CARD Rtd,2021-01-05,0,2.0,22.5,2,STD 500,500.000,2021-01-31,27,0.5,13.5,1.0
3,1.0,22.50,652.50,EXEMP427813,5,CBE STAFF CARD Rtd,2021-01-03,0,2.0,22.5,2,STD 500,500.000,2021-01-31,29,0.5,14.5,1.0
4,1.0,22.50,180.00,EXEMP10458,5,CBE STAFF CARD Rtd,2021-01-01,0,2.0,22.5,2,STD 500,500.000,2021-01-08,8,0.5,4.0,1.0

In [13]:
month = month
year = year
days = monthrange(year, month)
datetime_object = datetime.strptime(str(month), "%m")
month_name = datetime_object.strftime("%B")

datetime_object = datetime.strptime(str(month), "%m")
month_name = datetime_object.strftime("%B")

file_name = "monthly_supplied_milk_for_card_customer for ( " + str(month_name) + "-" + str(year) + " )" + '.pdf'
file_path = os.path.join('static/media', file_name)
mycanvas = canvas.Canvas(file_path, pagesize=(inch*14,inch*12))

mycanvas.setFont('Helvetica', 12.5)
mycanvas.drawCentredString(520, 840,
                           'The Coimbatore District Co-Operative Milk Producers Union Ltd, Pachapalayam, Coimbatore - 641 010')
mycanvas.setFont('Helvetica', 11)
mycanvas.drawCentredString(520, 815, 'Monthly Supplied Milk For Card Customer - ' + str(month_name) + "-" + str(year))

x_head = 20
y_head = 790


mycanvas.setFont('Helvetica', 10)
mycanvas.drawString(x_head,y_head,"PARTICULARS")
mycanvas.drawString(x_head+90,y_head,"MILK TYPE")
mycanvas.drawString(x_head+170,y_head,"AM")
mycanvas.drawString(x_head+230,y_head,"PM")
mycanvas.drawString(x_head+290,y_head,"TOTAL")
mycanvas.drawString(x_head+360,y_head,"QTY/DAY")
mycanvas.drawString(x_head+430,y_head,"DAYS")
mycanvas.drawString(x_head+480,y_head,"TOT.QTY")
mycanvas.drawString(x_head+545,y_head,"RATE/ltr")
mycanvas.drawString(x_head+600,y_head,"TOTAL VALUE")

mycanvas.drawString(x_head+690,y_head,"CUSTOMER CODE")
mycanvas.drawString(x_head+810,y_head,"FROM DATE")
mycanvas.drawString(x_head+910,y_head,"TO DATE")

mycanvas.setLineWidth(0)

#lines
mycanvas.line(x_head-5,y_head+15,x_head+980,y_head+15)
mycanvas.line(x_head-5,y_head-5,x_head+980,y_head-5)

x = 30
y = 765


mycanvas.setFont('Helvetica', 10)
# mycanvas.drawString(x,y,str(data))
am = 0
pm = 0
total = 0
qty_day = 0
total_qty = 0
total_value = 0
mycanvas.drawString(x-12,y,str('Card Sales'))
for datas in data_dict['Card Sales']:
    mycanvas.drawString(x+90,y,str(datas['product_name']))
    mycanvas.drawRightString(x+200,y,str(datas['am']))
    am += datas['am']

    mycanvas.drawRightString(x+260,y,str(datas['pm']))
    pm += datas['pm']

    mycanvas.drawRightString(x+330,y,str(datas['total_pockets_per_day']))
    total += datas['total_pockets_per_day']

    mycanvas.drawRightString(x+410,y,str(datas['total_ltrs_per_day']))
    qty_day += datas['total_ltrs_per_day']

    mycanvas.drawRightString(x+450,y,str(datas['total_days']))
    mycanvas.drawRightString(x+530,y,str(datas['total_ltrs_per_month']))
    total_qty += datas['total_ltrs_per_month']

    mycanvas.drawRightString(x+570,y,str(datas['product_cost']))
    mycanvas.drawRightString(x+665,y,str(datas['cost_for_month']))
    total_value += datas['cost_for_month']


    if datas['customer_code'] != 0:
        mycanvas.drawCentredString(x+725,y,str(datas['customer_code']))

    if datas['from_date'] != 0:
            from_date = datetime.strftime(datas['from_date'], '%d-%m-%Y')
            mycanvas.drawCentredString(x+830,y,str(from_date))

    if datas['to_date'] != 0:
        to_date = datetime.strftime(datas['to_date'], '%d-%m-%Y')
        mycanvas.drawCentredString(x+925,y,str(to_date))


    #lines
    mycanvas.line(x+70,y-5,x+970,y-5)

    mycanvas.line(x-15,y+40,x-15,y-25)
    mycanvas.line(x+70,y+40,x+70,y-25)
    mycanvas.line(x+140,y+40,x+140,y-25)

    mycanvas.line(x+205,y+40,x+205,y-25)
    mycanvas.line(x+265,y+40,x+265,y-25)
    mycanvas.line(x+335,y+40,x+335,y-25)
    mycanvas.line(x+415,y+40,x+415,y-25)
    mycanvas.line(x+455,y+40,x+455,y-25)
    mycanvas.line(x+535,y+40,x+535,y-25)
    mycanvas.line(x+575,y+40,x+575,y-25)
    mycanvas.line(x+670,y+40,x+670,y-25)

    mycanvas.line(x+780,y+40,x+780,y-25)
    mycanvas.line(x+875,y+40,x+875,y-25)
    mycanvas.line(x+970,y+40,x+970,y-25)

    y -= 20
mycanvas.line(x-15,y+15,x+70,y+15)
mycanvas.line(x_head-5,y-5,x_head+980,y-5)
mycanvas.drawString(x-10,y,"S U B T O T A L")

mycanvas.drawRightString(x+200,y,str(am))
mycanvas.drawRightString(x+260,y,str(pm))
mycanvas.drawRightString(x+330,y,str(total))
mycanvas.drawRightString(x+410,y,str(qty_day))
mycanvas.drawRightString(x+530,y,str(total_qty))
mycanvas.drawRightString(x+665,y,str(total_value))
y -= 20
#employees
am1 = 0
pm1 = 0
total1 = 0
qty_day1 = 0
total_qty1 = 0
total_value1 = 0
for data in data_dict["employees"]:
    mycanvas.setFont('Helvetica', 9)
    headding_split = data.split(' ')
    if len(headding_split) >= 4:
        data1 = headding_split[0] + ' '+ headding_split[1] +' '+ headding_split[2]
        data2 = headding_split[3]
        mycanvas.drawString(x-12,y,str(data1))
        mycanvas.drawString(x-12,y-15,str(data2))
    else:
        mycanvas.drawString(x-12,y,str(data))
    mycanvas.setFont('Helvetica', 10)
    for datas in data_dict["employees"][data]:
        if datas['cost_for_month'] == 0:
            continue
        mycanvas.drawString(x+90,y,str(datas['product_name']))
        mycanvas.drawRightString(x+200,y,str(datas['am']))
        am1 += datas['am']

        mycanvas.drawRightString(x+260,y,str(datas['pm']))
        pm1 += datas['pm']

        mycanvas.drawRightString(x+330,y,str(datas['total_pockets_per_day']))
        total1 += datas['total_pockets_per_day']

        mycanvas.drawRightString(x+410,y,str(datas['total_ltrs_per_day']))
        qty_day1 += datas['total_ltrs_per_day']

        mycanvas.drawRightString(x+450,y,str(datas['total_days']))
        mycanvas.drawRightString(x+530,y,str(datas['total_ltrs_per_month']))
        total_qty1 += datas['total_ltrs_per_month']

        mycanvas.drawRightString(x+570,y,str(datas['product_cost']))
        mycanvas.drawRightString(x+665,y,str(datas['cost_for_month']))
        total_value1 += datas['cost_for_month']

        if datas['customer_code'] != 0:
            mycanvas.drawCentredString(x+725,y,str(datas['customer_code']))

        if datas['from_date'] != 0:
            from_date = datetime.strftime(datas['from_date'], '%d-%m-%Y')
            mycanvas.drawCentredString(x+830,y,str(from_date))

        if datas['to_date'] != 0:
            to_date = datetime.strftime(datas['to_date'], '%d-%m-%Y')
            mycanvas.drawCentredString(x+925,y,str(to_date))

        #lines
        mycanvas.line(x+70,y-5,x+970,y-5)

        mycanvas.line(x-15,y+40,x-15,y-45)
        mycanvas.line(x+70,y+40,x+70,y-45)
        mycanvas.line(x+140,y+40,x+140,y-45)

        mycanvas.line(x+205,y+40,x+205,y-45)
        mycanvas.line(x+265,y+40,x+265,y-45)
        mycanvas.line(x+335,y+40,x+335,y-45)
        mycanvas.line(x+415,y+40,x+415,y-45)
        mycanvas.line(x+455,y+40,x+455,y-45)
        mycanvas.line(x+535,y+40,x+535,y-45)
        mycanvas.line(x+575,y+40,x+575,y-45)
        mycanvas.line(x+670,y+40,x+670,y-45)

        mycanvas.line(x+780,y+40,x+780,y-25)
        mycanvas.line(x+875,y+40,x+875,y-25)
        mycanvas.line(x+970,y+40,x+970,y-25)

        y -= 20
    mycanvas.line(x-15,y+15,x+70,y+15)
mycanvas.line(x-15,y+15,x+70,y+15)
mycanvas.line(x_head-5,y-5,x_head+980,y-5)
mycanvas.drawString(x-10,y,"S U B T O T A L")

mycanvas.drawRightString(x+200,y,str(am1))
mycanvas.drawRightString(x+260,y,str(pm1))
mycanvas.drawRightString(x+330,y,str(total1))
mycanvas.drawRightString(x+410,y,str(qty_day1))
mycanvas.drawRightString(x+530,y,str(total_qty1))
mycanvas.drawRightString(x+665,y,str(total_value1))

#total
mycanvas.drawRightString(x+200,y-20,str(am+am1))
mycanvas.drawRightString(x+260,y-20,str(pm+pm1))
mycanvas.drawRightString(x+330,y-20,str(total+total1))
mycanvas.drawRightString(x+410,y-20,str(qty_day+qty_day1))
mycanvas.drawRightString(x+530,y-20,str(total_qty+total_qty1))
mycanvas.drawRightString(x+665,y-20,str(float(total_value)+float(total_value1)))
mycanvas.line(x_head-5,y-25,x_head+680,y-25)
mycanvas.drawString(x-10,y-20,"T O T A L")
mycanvas.save()

In [9]:
{'Card Sales': {'TM 500': {'am': 4934,
   'pm': 2,
   'total': 4936,
   'qty/day': Decimal('2468.000'),
   'days': 31,
   'total/qty': Decimal('76508.000'),
   'rate': 20.0,
   'total_value': Decimal('3060320.00')},
  'STD 250': {'am': 3194,
   'pm': 194,
   'total': 3388,
   'qty/day': Decimal('847.000'),
   'days': 31,
   'total/qty': Decimal('26257.000'),
   'rate': 11.5,
   'total_value': Decimal('1207822.00')},
  'STD 500': {'am': 19579,
   'pm': 565,
   'total': 20144,
   'qty/day': Decimal('10072.000'),
   'days': 31,
   'total/qty': Decimal('312232.000'),
   'rate': 22.5,
   'total_value': Decimal('14050440.00')},
  'FCM 500': {'am': 1181,
   'pm': 0,
   'total': 1181,
   'qty/day': Decimal('590.500'),
   'days': 31,
   'total/qty': Decimal('18305.500'),
   'rate': 24.5,
   'total_value': Decimal('896969.50')}},
 'employees': {'STAFF CARD': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 311,
    'pm': 0,
    'total': 311,
    'qty/day': Decimal('155.500'),
    'days': 31,
    'total/qty': Decimal('4820.500'),
    'rate': 22.5,
    'total_value': Decimal('216922.50')}},
  'STAFF CARD Rtd': {'TM 500': {'am': 4,
    'pm': 0,
    'total': 4,
    'qty/day': Decimal('2.000'),
    'days': 31,
    'total/qty': Decimal('62.000'),
    'rate': 20.0,
    'total_value': Decimal('2480.00')},
   'STD 500': {'am': 208,
    'pm': 0,
    'total': 208,
    'qty/day': Decimal('104.000'),
    'days': 31,
    'total/qty': Decimal('3224.000'),
    'rate': 22.5,
    'total_value': Decimal('145080.00')}},
  'SC.TCMPF': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'tcmpf Rtd.Staff': {'TM 500': {'am': 18,
    'pm': 0,
    'total': 18,
    'qty/day': Decimal('9.000'),
    'days': 31,
    'total/qty': Decimal('279.000'),
    'rate': 20.0,
    'total_value': Decimal('11160.00')},
   'STD 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 22.5,
    'total_value': Decimal('3487.50')}},
  'NJF.OOTY': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'NDCMPU': {'TM 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 20.0,
    'total_value': Decimal('3100.00')},
   'STD 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0}},
  'MDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'EDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'TPRDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}}}}

{'Card Sales': {'TM 500': {'am': 4934,
   'pm': 2,
   'total': 4936,
   'qty/day': Decimal('2468.000'),
   'days': 31,
   'total/qty': Decimal('76508.000'),
   'rate': 20.0,
   'total_value': Decimal('3060320.00')},
  'STD 250': {'am': 3194,
   'pm': 194,
   'total': 3388,
   'qty/day': Decimal('847.000'),
   'days': 31,
   'total/qty': Decimal('26257.000'),
   'rate': 11.5,
   'total_value': Decimal('1207822.00')},
  'STD 500': {'am': 19579,
   'pm': 565,
   'total': 20144,
   'qty/day': Decimal('10072.000'),
   'days': 31,
   'total/qty': Decimal('312232.000'),
   'rate': 22.5,
   'total_value': Decimal('14050440.00')},
  'FCM 500': {'am': 1181,
   'pm': 0,
   'total': 1181,
   'qty/day': Decimal('590.500'),
   'days': 31,
   'total/qty': Decimal('18305.500'),
   'rate': 24.5,
   'total_value': Decimal('896969.50')}},
 'employees': {'STAFF CARD': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 311,
    'pm': 0,
    'total': 311,
    'qty/day': Decimal('155.500'),
    'days': 31,
    'total/qty': Decimal('4820.500'),
    'rate': 22.5,
    'total_value': Decimal('216922.50')}},
  'STAFF CARD Rtd': {'TM 500': {'am': 4,
    'pm': 0,
    'total': 4,
    'qty/day': Decimal('2.000'),
    'days': 31,
    'total/qty': Decimal('62.000'),
    'rate': 20.0,
    'total_value': Decimal('2480.00')},
   'STD 500': {'am': 208,
    'pm': 0,
    'total': 208,
    'qty/day': Decimal('104.000'),
    'days': 31,
    'total/qty': Decimal('3224.000'),
    'rate': 22.5,
    'total_value': Decimal('145080.00')}},
  'SC.TCMPF': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'tcmpf Rtd.Staff': {'TM 500': {'am': 18,
    'pm': 0,
    'total': 18,
    'qty/day': Decimal('9.000'),
    'days': 31,
    'total/qty': Decimal('279.000'),
    'rate': 20.0,
    'total_value': Decimal('11160.00')},
   'STD 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 22.5,
    'total_value': Decimal('3487.50')}},
  'NJF.OOTY': {'TM 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 20.0,
    'total_value': Decimal('620.00')},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'NDCMPU': {'TM 500': {'am': 5,
    'pm': 0,
    'total': 5,
    'qty/day': Decimal('2.500'),
    'days': 31,
    'total/qty': Decimal('77.500'),
    'rate': 20.0,
    'total_value': Decimal('3100.00')},
   'STD 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0}},
  'MDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}},
  'EDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 2,
    'pm': 0,
    'total': 2,
    'qty/day': Decimal('1.000'),
    'days': 31,
    'total/qty': Decimal('31.000'),
    'rate': 22.5,
    'total_value': Decimal('1395.00')}},
  'TPRDCMPU': {'TM 500': {'am': 0,
    'pm': 0,
    'total': 0,
    'qty/day': 0,
    'days': 0,
    'total/qty': 0,
    'rate': 0,
    'total_value': 0},
   'STD 500': {'am': 1,
    'pm': 0,
    'total': 1,
    'qty/day': Decimal('0.500'),
    'days': 31,
    'total/qty': Decimal('15.500'),
    'rate': 22.5,
    'total_value': Decimal('697.50')}}}}

In [7]:
ic_wallet_list = list(ICustomerWallet.objects.all().values_list('customer__customer_code', 'customer__user_profile__user__first_name',  'customer__business__code', 'customer__business__zone__name', 'current_balance'))                  
ic_wallet_column = ['Customer Code', 'Customer Name', 'Booth Code', 'Zone', 'Wallet Balance']
ic_df = pd.DataFrame(ic_wallet_list, columns=ic_wallet_column)
ic_df = ic_df[ic_df['Wallet Balance'] > 0]
ic_df

      Customer Code Customer Name Booth Code  Zone Wallet Balance
3482      CBE319288      Ramasamy       2197  EAST        1442.00
17123     CBE427551       jeyasri        325  WEST          85.00

In [4]:
df_from_excel = pd.read_excel('online-July 2020.xlsx')

# df_from_excel = df_from_excel.dropna(how='all', axis='columns')
excel_columns = df_from_excel.columns

# rename_columns
for column_name in excel_columns:
    new_column_name = column_name.lower()
    if " " in new_column_name:
        new_column_name = new_column_name.replace(' ', '_')
        if new_column_name[-1] == "_":
            new_column_name = new_column_name[:-1]

    df_from_excel = df_from_excel.rename(columns={column_name: new_column_name})

df_from_excel = df_from_excel.fillna(0)

df_from_excel = df_from_excel.rename(columns={'policy/crn_number':'crn', 'enquiry_id': 'rid'})
df_from_excel.columns

Index(['sr_no.', 'rid', 'company_reference', 'crn', 'txn_no', 'branch_code',
       'branch_name', 'total_amount', 'agg_pay_ref_id', 'mode_description',
       'cheque_number', 'cheque_date', 'micr_number', 'debit_acc_no',
       'clearance_date', 'clearance_flag', 'drawn_on_bank', 'drawn_on_branch',
       'pan_number', 'beneficary_acc_no', 'benificiary_name', 'ifsc_code',
       'txn_agg_code', 'settlement_date', 'settlement_status', 'tran_date',
       'settlement_amount', 'tranaction_id', 'transaction_pkey',
       'salegroup_id', 'booth_code', 'customer_code', 'product_list',
       'user_code', 'device_type', 'amount'],
      dtype='object')

In [3]:
bm_jar_sale_list = list(DailySessionllyBusinessllySale.objects.filter(business_type_id__in=[1,3]).values_list('delivery_date', 'business__code', 'bm_jar200_litre', 'bm_jar200_cost', 'bmjf200_litre'))                                         
bm_jar_sale_column = ['Delivery Date', 'Business Code', 'Bm Jar Ltr', 'Bm Jar Cost', 'Bm Jar Free Ltr']
bm_jar_sale_df = pd.DataFrame(bm_jar_sale_list, columns=bm_jar_sale_column)
bm_jar_sale_df = bm_jar_sale_df[bm_jar_sale_df['Bm Jar Free Ltr'] !=0]
bm_jar_sale_df['Bm Jar Free Cost'] = bm_jar_sale_df['Bm Jar Cost'].astype(float)/ bm_jar_sale_df['Bm Jar Ltr'].astype(float) * bm_jar_sale_df['Bm Jar Free Ltr'].astype(float)   

bm_jar_sale_df[['Bm Jar Ltr', 'Bm Jar Cost', 'Bm Jar Free Ltr', 'Bm Jar Free Cost']] = bm_jar_sale_df[['Bm Jar Ltr', 'Bm Jar Cost', 'Bm Jar Free Ltr', 'Bm Jar Free Cost']].astype(float)

bm_jar_sale_df = bm_jar_sale_df.sort_values(by=['Delivery Date'])
bm_jar_sale_df = bm_jar_sale_df.reset_index(drop=True)
bm_jar_sale_df.index += 1

In [4]:
bm_jar_sale_df.to_excel('butter_milk_jar_sale_details.xlsx')

### Date Range Wise Sale Report

In [12]:
from_date = '2021-05-1'
to_date = '2021-05-5'
business_code = 1881
sale_list  = list(SaleGroup.objects.filter(date__range=[from_date, to_date], business__code=business_code).values_list('date', 'sale__product__short_name', 'sale__product__quantity', 'sale__count', 'sale__cost', 'total_cost', 'session'))                                               
sale_column = ['date', 'product', 'quantity', 'count', 'cost', 'total_cost', 'session']
sale_df = pd.DataFrame(sale_list, columns=sale_column)
sale_df['litre'] = (sale_df['quantity'].astype(float)/1000)*sale_df['count'].astype(float)

product_dict = {}
for product in Product.objects.all().exclude(id__in=[21,22]):
    if not product.short_name in product_dict:
        product_dict[product.short_name] = {
            'mor':{
                'quantity': 0,
                'count': 0,
                'cost': 0,
                'litre': 0
            },
            'eve':{
                'quantity': 0,
                'count': 0,
                'cost': 0,
                'litre': 0
            }
        }

final_dict = {}
for index,value in sale_df.iterrows():
    if not str(value.date) in final_dict:
        final_dict[str(value.date)] = {}
        final_dict[str(value.date)]['sale'] = product_dict
        final_dict[str(value.date)]['total_amount'] = value.total_cost

    if value.session == 1:
        print(value['count'])
        final_dict[str(value.date)]['sale'][value['product']]['mor']['quantity'] = value['quantity']
        final_dict[str(value.date)]['sale'][value['product']]['mor']['count'] = value['count']
        final_dict[str(value.date)]['sale'][value['product']]['mor']['cost'] = value['cost']
        final_dict[str(value.date)]['sale'][value['product']]['mor']['litre'] = round(Decimal(value['litre']), 3)


#     if value.session == 2:
#         final_dict[str(value.date)]['sale'][value['product']]['eve']['quantity'] = value['quantity']
#         final_dict[str(value.date)]['sale'][value['product']]['eve']['count'] += value['count']
#         final_dict[str(value.date)]['sale'][value['product']]['eve']['cost'] += value['cost']
#         final_dict[str(value.date)]['sale'][value['product']]['eve']['litre'] += round(Decimal(value['litre']), 3)
final_dict

264.0
192.0
34.0
168.0
240.0
32.0
132.0
180.0
32.0
204.0
192.0
32.0
192.0
192.0
34.0

{'2021-05-01': {'sale': {'Curd 100': {'mor': {'quantity': 0,
     'count': 0,
     'cost': 0,
     'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Lassi 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJF': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'SMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 150': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BM 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJar': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'TM 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 192.0,
     'cost': Decimal('4512.00'),
     'litre': Decimal('96.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 250': {'mor': {'quantity': Decimal('250.000'),
     'count': 192.0,
     'cost': Decimal('2304.00'),
     'litre': Decimal('48.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 34.0,
     'cost': Decimal('867.00'),
     'litre': Decimal('17.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 1000': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}}},
  'total_amount': Decimal('9375.00')},
 '2021-05-02': {'sale': {'Curd 100': {'mor': {'quantity': 0,
     'count': 0,
     'cost': 0,
     'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Lassi 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJF': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'SMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 150': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BM 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJar': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'TM 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 192.0,
     'cost': Decimal('4512.00'),
     'litre': Decimal('96.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 250': {'mor': {'quantity': Decimal('250.000'),
     'count': 192.0,
     'cost': Decimal('2304.00'),
     'litre': Decimal('48.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 34.0,
     'cost': Decimal('867.00'),
     'litre': Decimal('17.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 1000': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}}},
  'total_amount': Decimal('7644.00')},
 '2021-05-03': {'sale': {'Curd 100': {'mor': {'quantity': 0,
     'count': 0,
     'cost': 0,
     'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Lassi 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJF': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'SMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 150': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BM 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJar': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'TM 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 192.0,
     'cost': Decimal('4512.00'),
     'litre': Decimal('96.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 250': {'mor': {'quantity': Decimal('250.000'),
     'count': 192.0,
     'cost': Decimal('2304.00'),
     'litre': Decimal('48.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 34.0,
     'cost': Decimal('867.00'),
     'litre': Decimal('17.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 1000': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}}},
  'total_amount': Decimal('6078.00')},
 '2021-05-04': {'sale': {'Curd 100': {'mor': {'quantity': 0,
     'count': 0,
     'cost': 0,
     'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Lassi 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJF': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'SMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 150': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BM 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJar': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'TM 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 192.0,
     'cost': Decimal('4512.00'),
     'litre': Decimal('96.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 250': {'mor': {'quantity': Decimal('250.000'),
     'count': 192.0,
     'cost': Decimal('2304.00'),
     'litre': Decimal('48.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 34.0,
     'cost': Decimal('867.00'),
     'litre': Decimal('17.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 1000': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}}},
  'total_amount': Decimal('7914.00')},
 '2021-05-05': {'sale': {'Curd 100': {'mor': {'quantity': 0,
     'count': 0,
     'cost': 0,
     'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Lassi 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJF': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'SMcan': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 150': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'Curd 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BM 200': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'BMJar': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'TM 500': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 192.0,
     'cost': Decimal('4512.00'),
     'litre': Decimal('96.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'STD 250': {'mor': {'quantity': Decimal('250.000'),
     'count': 192.0,
     'cost': Decimal('2304.00'),
     'litre': Decimal('48.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 500': {'mor': {'quantity': Decimal('500.000'),
     'count': 34.0,
     'cost': Decimal('867.00'),
     'litre': Decimal('17.000')},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}},
   'FCM 1000': {'mor': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0},
    'eve': {'quantity': 0, 'count': 0, 'cost': 0, 'litre': 0}}},
  'total_amount': Decimal('7683.00')}}

In [6]:
sale_df

          date  product quantity  count     cost total_cost  session  litre
0   2021-05-01  STD 500  500.000  264.0  6204.00    9375.00        1  132.0
1   2021-05-01  STD 250  250.000  192.0  2304.00    9375.00        1   48.0
2   2021-05-01  FCM 500  500.000   34.0   867.00    9375.00        1   17.0
3   2021-05-01  STD 500  500.000  168.0  3948.00    4812.00        2   84.0
4   2021-05-01  STD 250  250.000   72.0   864.00    4812.00        2   18.0
5   2021-05-02  STD 500  500.000  168.0  3948.00    7644.00        1   84.0
6   2021-05-02  STD 250  250.000  240.0  2880.00    7644.00        1   60.0
7   2021-05-02  FCM 500  500.000   32.0   816.00    7644.00        1   16.0
8   2021-05-02  STD 500  500.000  144.0  3384.00    4248.00        2   72.0
9   2021-05-02  STD 250  250.000   72.0   864.00    4248.00        2   18.0
10  2021-05-03  STD 500  500.000  132.0  3102.00    6078.00        1   66.0
11  2021-05-03  STD 250  250.000  180.0  2160.00    6078.00        1   45.0
12  2021-05-03  FCM 500  500.000   32.0   816.00    6078.00        1   16.0
13  2021-05-03  STD 500  500.000  120.0  2820.00    3540.00        2   60.0
14  2021-05-03  STD 250  250.000   60.0   720.00    3540.00        2   15.0
15  2021-05-04  STD 500  500.000  204.0  4794.00    7914.00        1  102.0
16  2021-05-04  STD 250  250.000  192.0  2304.00    7914.00        1   48.0
17  2021-05-04  FCM 500  500.000   32.0   816.00    7914.00        1   16.0
18  2021-05-04  STD 500  500.000  120.0  2820.00    3540.00        2   60.0
19  2021-05-04  STD 250  250.000   60.0   720.00    3540.00        2   15.0
20  2021-05-05  STD 500  500.000  192.0  4512.00    7683.00        1   96.0
21  2021-05-05  STD 250  250.000  192.0  2304.00    7683.00        1   48.0
22  2021-05-05  FCM 500  500.000   34.0   867.00    7683.00        1   17.0
23  2021-05-05  STD 500  500.000  120.0  2820.00    3540.00        2   60.0
24  2021-05-05  STD 250  250.000   60.0   720.00    3540.00        2   15.0